import assert from 'node:assert/strict';
import test, { before, after, beforeEach } from 'node:test';
import { newDb } from 'pg-mem';
import { setPoolForTesting, resetPoolForTesting } from '../db/pool.js';

// Repository/service tests run against pg-mem (an in-memory Postgres emulator) executing the
// REAL notify.* table/constraint shapes from database/10_notify_tables.sql and their FK targets
// from database/02_org_tables.sql / 03_iam_tables.sql / 04_work_tables.sql — trimmed to the
// columns these tests actually exercise (pg-mem doesn't support every Postgres feature the full
// 70-table schema uses, e.g. GENERATED ALWAYS AS IDENTITY nuances and the PL/pgSQL support
// functions from 01_support_functions.sql, so SERIAL/BIGSERIAL stand in for
// GENERATED BY DEFAULT AS IDENTITY here). This is a test-only fixture — the real server always
// runs against the actual database/*.sql files via `psql -f database/setup.sql`, never this.
//
// No live Postgres/Docker was available in this environment (see the DB testing approach
// agreed with the user before this branch started) — this is the closest verification possible
// without one: real SQL, real constraints, real repository code, just an in-memory engine.

const SCHEMA_DDL = `
  CREATE SCHEMA org;
  CREATE SCHEMA iam;
  CREATE SCHEMA work;
  CREATE SCHEMA hr;
  CREATE SCHEMA notify;

  CREATE TABLE org.Organizations (
    OrganizationId SERIAL PRIMARY KEY,
    OrganizationCode VARCHAR(30) NOT NULL
  );

  CREATE TABLE iam.Users (
    UserId SERIAL PRIMARY KEY,
    OrganizationId INT NOT NULL REFERENCES org.Organizations(OrganizationId),
    Email VARCHAR(254) NOT NULL,
    DisplayName VARCHAR(170) NOT NULL,
    AccountStatus VARCHAR(20) NOT NULL DEFAULT 'Active'
  );

  CREATE TABLE work.ProjectStatuses (
    ProjectStatusId SERIAL PRIMARY KEY,
    StatusCode VARCHAR(30) NOT NULL UNIQUE
  );

  CREATE TABLE work.TaskStatuses (
    TaskStatusId SERIAL PRIMARY KEY,
    StatusCode VARCHAR(30) NOT NULL UNIQUE
  );

  CREATE TABLE work.Priorities (
    PriorityId SERIAL PRIMARY KEY,
    PriorityCode VARCHAR(20) NOT NULL UNIQUE
  );

  CREATE TABLE work.Projects (
    ProjectId SERIAL PRIMARY KEY,
    OrganizationId INT NOT NULL REFERENCES org.Organizations(OrganizationId),
    ProjectCode VARCHAR(30) NOT NULL,
    ProjectName VARCHAR(150) NOT NULL,
    OwnerUserId INT NOT NULL REFERENCES iam.Users(UserId),
    ProjectStatusId SMALLINT NOT NULL REFERENCES work.ProjectStatuses(ProjectStatusId),
    PriorityId SMALLINT NOT NULL REFERENCES work.Priorities(PriorityId)
  );

  CREATE TABLE work.Tasks (
    TaskId BIGSERIAL PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES work.Projects(ProjectId),
    Title VARCHAR(200) NOT NULL,
    TaskStatusId SMALLINT NOT NULL REFERENCES work.TaskStatuses(TaskStatusId),
    PriorityId SMALLINT NOT NULL REFERENCES work.Priorities(PriorityId)
  );

  CREATE TABLE work.TaskChangeRequests (
    ChangeRequestId BIGSERIAL PRIMARY KEY
  );

  CREATE TABLE hr.AttendanceCorrectionRequests (
    AttendanceCorrectionId BIGSERIAL PRIMARY KEY
  );

  CREATE TABLE hr.LeaveRequests (
    LeaveRequestId BIGSERIAL PRIMARY KEY
  );

  CREATE TABLE notify.NotificationTypes (
    NotificationTypeId SERIAL PRIMARY KEY,
    -- Real schema (database/10_notify_tables.sql) has TypeCode UNIQUE. Deliberately omitted here:
    -- pg-mem mishandles "WHERE col = ANY($::text[])" joined via LEFT JOIN when col carries a
    -- UNIQUE constraint — it silently returns zero rows instead of the matching ones (verified
    -- with a minimal repro outside this suite; the same query against real Postgres, or against
    -- this column without UNIQUE, returns correctly). Test-only DDL simplification, not a
    -- production behavior change — getPreferencesForTypes' production query is unaffected.
    TypeCode VARCHAR(50) NOT NULL,
    CategoryCode VARCHAR(30) NOT NULL,
    DefaultPriority VARCHAR(10) NOT NULL,
    IsMandatory BOOLEAN NOT NULL DEFAULT FALSE,
    DefaultEnabled BOOLEAN NOT NULL DEFAULT TRUE
  );

  CREATE TABLE notify.UserNotificationPreferences (
    UserId INT NOT NULL REFERENCES iam.Users(UserId),
    NotificationTypeId SMALLINT NOT NULL REFERENCES notify.NotificationTypes(NotificationTypeId),
    InAppEnabled BOOLEAN NOT NULL DEFAULT TRUE,
    EmailEnabled BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (UserId, NotificationTypeId)
  );

  CREATE TABLE notify.Notifications (
    NotificationId BIGSERIAL PRIMARY KEY,
    NotificationTypeId SMALLINT NOT NULL REFERENCES notify.NotificationTypes(NotificationTypeId),
    ActorUserId INT NULL REFERENCES iam.Users(UserId),
    ProjectId INT NULL REFERENCES work.Projects(ProjectId),
    TaskId BIGINT NULL REFERENCES work.Tasks(TaskId),
    ChangeRequestId BIGINT NULL REFERENCES work.TaskChangeRequests(ChangeRequestId),
    AttendanceCorrectionId BIGINT NULL REFERENCES hr.AttendanceCorrectionRequests(AttendanceCorrectionId),
    LeaveRequestId BIGINT NULL REFERENCES hr.LeaveRequests(LeaveRequestId),
    Title VARCHAR(200) NOT NULL,
    SafePreviewText VARCHAR(500) NULL,
    PriorityCode VARCHAR(10) NOT NULL,
    CreatedAtUtc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE notify.UserNotifications (
    NotificationId BIGINT NOT NULL REFERENCES notify.Notifications(NotificationId),
    RecipientUserId INT NOT NULL REFERENCES iam.Users(UserId),
    DeliveryStatus VARCHAR(20) NOT NULL DEFAULT 'Pending',
    DeliveredAtUtc TIMESTAMPTZ NULL,
    ReadAtUtc TIMESTAMPTZ NULL,
    OpenedAtUtc TIMESTAMPTZ NULL,
    ClearedAtUtc TIMESTAMPTZ NULL,
    PRIMARY KEY (NotificationId, RecipientUserId)
  );
`;

const SEED_DML = `
  INSERT INTO org.Organizations (OrganizationCode) VALUES ('WORKSYNC');
  INSERT INTO iam.Users (OrganizationId, Email, DisplayName) VALUES
    (1, 'admin@test.com', 'Admin User'),
    (1, 'lead@test.com', 'Team Lead User'),
    (1, 'member@test.com', 'Team Member User');
  INSERT INTO work.ProjectStatuses (StatusCode) VALUES ('Active');
  INSERT INTO work.TaskStatuses (StatusCode) VALUES ('Todo');
  INSERT INTO work.Priorities (PriorityCode) VALUES ('Medium'), ('High');
  INSERT INTO work.Projects (OrganizationId, ProjectCode, ProjectName, OwnerUserId, ProjectStatusId, PriorityId)
    VALUES (1, 'PROJ-1', 'Test Project', 2, 1, 1);
  INSERT INTO work.Tasks (ProjectId, Title, TaskStatusId, PriorityId) VALUES (1, 'Test Task', 1, 2);
  INSERT INTO notify.NotificationTypes (TypeCode, CategoryCode, DefaultPriority) VALUES
    ('task_assigned', 'Task', 'High'),
    ('system', 'System', 'Low'),
    ('mention', 'Chat', 'Normal'),
    ('comment_added', 'Task', 'Normal'),
    ('task_due_tomorrow', 'Task', 'Normal');
`;

let db: ReturnType<typeof newDb>;

before(() => {
  db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.none(SCHEMA_DDL);
  db.public.none(SEED_DML);
  const { Pool } = db.adapters.createPg();
  setPoolForTesting(new Pool());
});

after(() => {
  resetPoolForTesting();
});

// Each test starts from a clean slate: wipe every notification/preference row written by the
// previous test, but leave the reference data (users/projects/tasks/notification types) alone.
// (An earlier version of this used db.backup()/.restore(), but that snapshot is taken against the
// raw IMemoryDb while all queries run through a pg Pool created once in before() — restoring left
// that Pool's live query path out of sync with the restored snapshot, so rows kept accumulating
// across tests. Explicit deletes have no such indirection.)
beforeEach(() => {
  db.public.none(`
    DELETE FROM notify.UserNotifications;
    DELETE FROM notify.Notifications;
    DELETE FROM notify.UserNotificationPreferences;
  `);
});

test('idMapping + repository: getNotificationTypeMeta returns seeded type', async () => {
  const repo = await import('./notification.repository.js');
  const meta = await repo.getNotificationTypeMeta('task_assigned');
  assert.ok(meta);
  assert.equal(meta!.categoryCode, 'Task');
  assert.equal(meta!.defaultPriority, 'High');
});

test('publishEvent: creates a Notification + fans out to all recipients', async () => {
  const service = await import('./notification.service.js');
  const created = await service.publishEvent({
    type: 'task_assigned',
    title: 'New Task Assigned',
    message: 'Admin User assigned you "Test Task" in Test Project.',
    recipientIds: ['usr-2', 'usr-3'],
    actorId: 'usr-1',
    projectId: 'prj-1',
    taskId: 'tsk-1'
  });

  assert.equal(created.length, 2);
  assert.deepEqual(created.map((n) => n.userId).sort(), ['usr-2', 'usr-3']);
  assert.equal(created[0].type, 'task_assigned');
  assert.equal(created[0].priority, 'High');
  assert.equal(created[0].read, false);
});

test('getNotificationsForUser: recipient sees their own notification, not others\'', async () => {
  const service = await import('./notification.service.js');
  await service.publishEvent({
    type: 'task_assigned',
    title: 'New Task Assigned',
    message: 'Assigned to usr-2.',
    recipientIds: ['usr-2'],
    actorId: 'usr-1'
  });

  const forRecipient = await service.getNotificationsForUser('usr-2');
  assert.equal(forRecipient.items.length, 1);
  assert.equal(forRecipient.items[0].userId, 'usr-2');
  assert.equal(forRecipient.items[0].actorId, 'usr-1');

  const forUnrelatedUser = await service.getNotificationsForUser('usr-3');
  assert.equal(forUnrelatedUser.items.length, 0);
});

test('markNotificationRead: read state is tracked independently per recipient', async () => {
  const service = await import('./notification.service.js');
  // Both usr-2 and usr-3 are recipients of the SAME broadcast event, so per the schema
  // (notify.Notifications is 1:N to notify.UserNotifications) they legitimately share one
  // NotificationId — each recipient's read state lives on their own UserNotifications row.
  const created = await service.publishEvent({
    type: 'task_assigned',
    title: 'New Task Assigned',
    message: 'Assigned.',
    recipientIds: ['usr-2', 'usr-3']
  });
  const notificationId = created[0].id;
  assert.equal(created[1].id, notificationId, 'both recipients should share one NotificationId');

  const usr3Result = await service.markNotificationRead('usr-3', notificationId);
  assert.equal(usr3Result, true, 'usr-3 owns a copy of this shared notification and can mark it read');

  const { items: usr3Items } = await service.getNotificationsForUser('usr-3');
  assert.equal(usr3Items[0].read, true);

  const { items: usr2Items } = await service.getNotificationsForUser('usr-2');
  assert.equal(usr2Items[0].read, false, 'usr-2\'s own copy must be unaffected by usr-3 marking theirs read');

  // usr-1 (the actor) has no UserNotifications row at all for this id — ownership is enforced by
  // the UPDATE...WHERE clause itself (FR-24), so this must be rejected rather than silently no-op.
  const unrelatedResult = await service.markNotificationRead('usr-1', notificationId);
  assert.equal(unrelatedResult, false, 'a non-recipient has no row to update and cannot mark it read');
});

test('markAllNotificationsRead: only affects the calling user\'s own notifications', async () => {
  const service = await import('./notification.service.js');
  await service.publishEvent({
    type: 'task_assigned',
    title: 'A',
    message: 'A',
    recipientIds: ['usr-2', 'usr-3']
  });
  await service.publishEvent({
    type: 'task_assigned',
    title: 'B',
    message: 'B',
    recipientIds: ['usr-2']
  });

  const count = await service.markAllNotificationsRead('usr-2');
  assert.equal(count, 2);

  const { items: usr3Items } = await service.getNotificationsForUser('usr-3');
  assert.equal(usr3Items.every((n) => !n.read), true, 'usr-3\'s notifications must remain unread');
});

test('clearNotification: soft-deletes (excluded from future queries) without a hard DELETE', async () => {
  const service = await import('./notification.service.js');
  const created = await service.publishEvent({
    type: 'task_assigned',
    title: 'A',
    message: 'A',
    recipientIds: ['usr-2']
  });

  const cleared = await service.clearNotification('usr-2', created[0].id);
  assert.equal(cleared, true);

  const { items } = await service.getNotificationsForUser('usr-2');
  assert.equal(items.length, 0);
});

test('preferences: disabling "assignments" suppresses task_assigned in-app delivery', async () => {
  const service = await import('./notification.service.js');

  await service.updatePreferences('usr-2', { assignments: false });
  await service.publishEvent({
    type: 'task_assigned',
    title: 'Suppressed for usr-2',
    message: 'Should be suppressed for usr-2, delivered for usr-3.',
    recipientIds: ['usr-2', 'usr-3']
  });

  const { items: usr2Items } = await service.getNotificationsForUser('usr-2');
  assert.equal(usr2Items.length, 0, 'usr-2 disabled assignments — should not see it');

  const { items: usr3Items } = await service.getNotificationsForUser('usr-3');
  assert.equal(usr3Items.length, 1, 'usr-3 never changed preferences — should still see it');
});

test('preferences: master inApp=false suppresses every type, not just categorized ones', async () => {
  const service = await import('./notification.service.js');

  await service.updatePreferences('usr-2', { inApp: false });
  await service.publishEvent({
    type: 'system',
    title: 'System notice',
    message: 'Uncategorized type, still gated by the master switch.',
    recipientIds: ['usr-2']
  });

  const { items } = await service.getNotificationsForUser('usr-2');
  assert.equal(items.length, 0);
});

test('getPreferences: defaults to enabled in-app / disabled email with no prior row', async () => {
  const service = await import('./notification.service.js');
  const prefs = await service.getPreferences('usr-3');
  assert.equal(prefs.inApp, true);
  assert.equal(prefs.assignments, true);
  assert.equal(prefs.email, false);
});
