-- Tables owned by the org schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE org.Organizations
(
    OrganizationId      int GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Organizations PRIMARY KEY,
    OrganizationCode    varchar(30) NOT NULL,
    OrganizationName    varchar(150) NOT NULL,
    TimeZoneId           varchar(100) NOT NULL CONSTRAINT DF_Organizations_TimeZone DEFAULT ('Asia/Karachi'),
    IsActive             boolean NOT NULL CONSTRAINT DF_Organizations_IsActive DEFAULT TRUE,
    CreatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_Organizations_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_Organizations_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion           bigint NOT NULL DEFAULT 1,
    CONSTRAINT UQ_Organizations_Code UNIQUE (OrganizationCode),
    CONSTRAINT CK_Organizations_Code CHECK (char_length(btrim(OrganizationCode)) > 0),
    CONSTRAINT CK_Organizations_Name CHECK (char_length(btrim(OrganizationName)) > 0)
);

CREATE TABLE org.Departments
(
    DepartmentId         int GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Departments PRIMARY KEY,
    OrganizationId       INT NOT NULL,
    ParentDepartmentId   INT NULL,
    DepartmentCode       varchar(30) NOT NULL,
    DepartmentName       varchar(120) NOT NULL,
    Description          varchar(500) NULL,
    IsActive             boolean NOT NULL CONSTRAINT DF_Departments_IsActive DEFAULT TRUE,
    CreatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_Departments_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_Departments_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion           bigint NOT NULL DEFAULT 1,
    CONSTRAINT UQ_Departments_Organization_Code UNIQUE (OrganizationId, DepartmentCode),
    CONSTRAINT UQ_Departments_Id_Organization UNIQUE (DepartmentId, OrganizationId),
    CONSTRAINT CK_Departments_NoSelfParent CHECK (ParentDepartmentId IS NULL OR ParentDepartmentId <> DepartmentId),
    CONSTRAINT CK_Departments_Code CHECK (char_length(btrim(DepartmentCode)) > 0),
    CONSTRAINT CK_Departments_Name CHECK (char_length(btrim(DepartmentName)) > 0)
);

CREATE TABLE org.Teams
(
    TeamId               int GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Teams PRIMARY KEY,
    DepartmentId         INT NOT NULL,
    TeamCode             varchar(30) NOT NULL,
    TeamName             varchar(120) NOT NULL,
    Description          varchar(500) NULL,
    IsActive             boolean NOT NULL CONSTRAINT DF_Teams_IsActive DEFAULT TRUE,
    CreatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_Teams_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_Teams_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion           bigint NOT NULL DEFAULT 1,
    CONSTRAINT UQ_Teams_Department_Code UNIQUE (DepartmentId, TeamCode),
    CONSTRAINT CK_Teams_Code CHECK (char_length(btrim(TeamCode)) > 0),
    CONSTRAINT CK_Teams_Name CHECK (char_length(btrim(TeamName)) > 0)
);
