-- Tables owned by the iam schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE iam.Users
(
    UserId               int GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Users PRIMARY KEY,
    OrganizationId       INT NOT NULL,
    DepartmentId         INT NULL,
    ManagerUserId        INT NULL,
    EmployeeNumber       varchar(40) NULL,
    Email                 varchar(254) NOT NULL,
    GivenName             varchar(80) NOT NULL,
    FamilyName            varchar(80) NOT NULL,
    DisplayName           varchar(170) NOT NULL,
    Designation           varchar(120) NULL,
    AccountStatus         VARCHAR(20) NOT NULL CONSTRAINT DF_Users_Status DEFAULT ('Active'),
    LastLoginAtUtc        timestamptz(0) NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_Users_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_Users_Updated DEFAULT (CURRENT_TIMESTAMP),
    DeactivatedAtUtc      timestamptz(0) NULL,
    RowVersion            bigint NOT NULL DEFAULT 1,
    CONSTRAINT UQ_Users_Organization_Email UNIQUE (OrganizationId, Email),
    CONSTRAINT UQ_Users_Id_Organization UNIQUE (UserId, OrganizationId),
    CONSTRAINT CK_Users_Email CHECK (Email LIKE '%_@_%._%' AND Email NOT LIKE '% %'),
    CONSTRAINT CK_Users_Names CHECK
            (char_length(btrim(GivenName)) > 0 AND char_length(btrim(FamilyName)) > 0 AND char_length(btrim(DisplayName)) > 0),
    CONSTRAINT CK_Users_Status CHECK (AccountStatus IN ('Pending','Active','Locked','Deactivated')),
    CONSTRAINT CK_Users_Deactivated CHECK
            ((AccountStatus = 'Deactivated' AND DeactivatedAtUtc IS NOT NULL) OR AccountStatus <> 'Deactivated'),
    CONSTRAINT CK_Users_NoSelfManager CHECK (ManagerUserId IS NULL OR ManagerUserId <> UserId)
);

CREATE TABLE iam.UserProfiles
(
    UserId               INT CONSTRAINT PK_UserProfiles PRIMARY KEY,
    PhoneNumber          varchar(30) NULL,
    AboutText            varchar(1000) NULL,
    PreferredName        varchar(80) NULL,
    LocaleCode           VARCHAR(15) NOT NULL CONSTRAINT DF_UserProfiles_Locale DEFAULT ('en-PK'),
    TimeZoneId           varchar(100) NULL,
    ProfileImageFileId   BIGINT NULL,
    /* FK added after file table */
        UpdatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_UserProfiles_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion           bigint NOT NULL DEFAULT 1
);

CREATE TABLE iam.UserCredentials
(
    UserId               INT CONSTRAINT PK_UserCredentials PRIMARY KEY,
    PasswordHash         bytea NOT NULL,
    PasswordAlgorithm    VARCHAR(30) NOT NULL,
    PasswordChangedAtUtc timestamptz(0) NOT NULL CONSTRAINT DF_UserCredentials_Changed DEFAULT (CURRENT_TIMESTAMP),
    FailedAttemptCount   SMALLINT NOT NULL CONSTRAINT DF_UserCredentials_Failed DEFAULT (0),
    LockedUntilUtc       timestamptz(0) NULL,
    MustChangePassword   boolean NOT NULL CONSTRAINT DF_UserCredentials_MustChange DEFAULT FALSE,
    CONSTRAINT CK_UserCredentials_Attempts CHECK (FailedAttemptCount >= 0)
);

CREATE TABLE iam.Roles
(
    RoleId               smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Roles PRIMARY KEY,
    RoleCode             VARCHAR(40) NOT NULL CONSTRAINT UQ_Roles_Code UNIQUE,
    RoleName             varchar(80) NOT NULL,
    IsSystemRole         boolean NOT NULL CONSTRAINT DF_Roles_System DEFAULT TRUE,
    IsTemporary          boolean NOT NULL CONSTRAINT DF_Roles_Temporary DEFAULT FALSE,
    Description          varchar(500) NULL,
    CONSTRAINT CK_Roles_Code CHECK (char_length(btrim(RoleCode)) > 0),
    CONSTRAINT CK_Roles_Name CHECK (char_length(btrim(RoleName)) > 0)
);

CREATE TABLE iam.Permissions
(
    PermissionId         smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Permissions PRIMARY KEY,
    PermissionCode       VARCHAR(80) NOT NULL CONSTRAINT UQ_Permissions_Code UNIQUE,
    PermissionName       varchar(120) NOT NULL,
    ModuleCode           VARCHAR(40) NOT NULL,
    Description          varchar(500) NULL,
    CONSTRAINT CK_Permissions_Code CHECK (char_length(btrim(PermissionCode)) > 0),
    CONSTRAINT CK_Permissions_Module CHECK (char_length(btrim(ModuleCode)) > 0)
);

CREATE TABLE iam.RolePermissions
(
    RoleId               SMALLINT NOT NULL,
    PermissionId         SMALLINT NOT NULL,
    CONSTRAINT PK_RolePermissions PRIMARY KEY (RoleId, PermissionId)
);

CREATE TABLE iam.UserRoles
(
    UserRoleId           bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_UserRoles PRIMARY KEY,
    UserId               INT NOT NULL,
    RoleId               SMALLINT NOT NULL,
    GrantedByUserId      INT NOT NULL,
    StartsAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_UserRoles_Start DEFAULT (CURRENT_TIMESTAMP),
    EndsAtUtc            timestamptz(0) NULL,
    RevokedAtUtc         timestamptz(0) NULL,
    RevokedByUserId      INT NULL,
    RevocationReason     varchar(500) NULL,
    CreatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_UserRoles_Created DEFAULT (CURRENT_TIMESTAMP),
    RowVersion           bigint NOT NULL DEFAULT 1,
    CONSTRAINT CK_UserRoles_Dates CHECK (EndsAtUtc IS NULL OR EndsAtUtc > StartsAtUtc),
    CONSTRAINT CK_UserRoles_NoSelfGrant CHECK (UserId <> GrantedByUserId),
    CONSTRAINT CK_UserRoles_Revocation CHECK
            ((RevokedAtUtc IS NULL AND RevokedByUserId IS NULL) OR
             (RevokedAtUtc IS NOT NULL AND RevokedByUserId IS NOT NULL AND char_length(btrim(RevocationReason)) > 0))
);

CREATE TABLE iam.PermissionAssignmentHistory
(
    PermissionHistoryId bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_PermissionAssignmentHistory PRIMARY KEY,
    UserRoleId           BIGINT NOT NULL,
    ActionCode           VARCHAR(20) NOT NULL,
    ActorUserId          INT NOT NULL,
    PreviousEndsAtUtc    timestamptz(0) NULL,
    NewEndsAtUtc         timestamptz(0) NULL,
    Reason               varchar(500) NULL,
    OccurredAtUtc        timestamptz(0) NOT NULL CONSTRAINT DF_PermissionHistory_Occurred DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT CK_PermissionHistory_Action CHECK (ActionCode IN ('Granted','Extended','ScopeChanged','Expired','Revoked','Restored'))
);

CREATE TABLE iam.TeamLeadProjectScopes
(
    UserRoleId           BIGINT NOT NULL,
    ProjectId            INT NOT NULL,
    CanCreateTasks       boolean NOT NULL CONSTRAINT DF_TeamLeadScopes_CreateTasks DEFAULT TRUE,
    CanManageMembers     boolean NOT NULL CONSTRAINT DF_TeamLeadScopes_Members DEFAULT TRUE,
    CanArchiveProject    boolean NOT NULL CONSTRAINT DF_TeamLeadScopes_Archive DEFAULT FALSE,
    CanDeleteTasks       boolean NOT NULL CONSTRAINT DF_TeamLeadScopes_DeleteTasks DEFAULT FALSE,
    RequiresActivation   boolean NOT NULL CONSTRAINT DF_TeamLeadScopes_Activation DEFAULT FALSE,
    CONSTRAINT PK_TeamLeadProjectScopes PRIMARY KEY (UserRoleId, ProjectId)
);

CREATE TABLE iam.HrDepartmentScopes
(
    UserRoleId            BIGINT NOT NULL,
    DepartmentId          INT NOT NULL,
    CanExportAttendance   boolean NOT NULL CONSTRAINT DF_HrScopes_Export DEFAULT TRUE,
    CONSTRAINT PK_HrDepartmentScopes PRIMARY KEY (UserRoleId, DepartmentId)
);
