-- Tables owned by the work schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE work.ProjectStatuses
(
    ProjectStatusId      smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ProjectStatuses PRIMARY KEY,
    StatusCode           VARCHAR(30) NOT NULL CONSTRAINT UQ_ProjectStatuses_Code UNIQUE,
    StatusName           varchar(80) NOT NULL,
    SortOrder            SMALLINT NOT NULL,
    IsActiveState        boolean NOT NULL,
    IsTerminalState      boolean NOT NULL CONSTRAINT DF_ProjectStatuses_Terminal DEFAULT FALSE,
    CONSTRAINT UQ_ProjectStatuses_Order UNIQUE (SortOrder),
    CONSTRAINT CK_ProjectStatuses_Order CHECK (SortOrder >= 0)
);

CREATE TABLE work.TaskStatuses
(
    TaskStatusId         smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_TaskStatuses PRIMARY KEY,
    StatusCode           VARCHAR(30) NOT NULL CONSTRAINT UQ_TaskStatuses_Code UNIQUE,
    StatusName           varchar(80) NOT NULL,
    SortOrder            SMALLINT NOT NULL,
    IsCompletedState     boolean NOT NULL CONSTRAINT DF_TaskStatuses_Completed DEFAULT FALSE,
    RequiresBlocker      boolean NOT NULL CONSTRAINT DF_TaskStatuses_Blocker DEFAULT FALSE,
    RequiresReview       boolean NOT NULL CONSTRAINT DF_TaskStatuses_Review DEFAULT FALSE,
    IsEnabled            boolean NOT NULL CONSTRAINT DF_TaskStatuses_Enabled DEFAULT TRUE,
    CONSTRAINT UQ_TaskStatuses_Order UNIQUE (SortOrder),
    CONSTRAINT CK_TaskStatuses_Order CHECK (SortOrder >= 0)
);

CREATE TABLE work.Priorities
(
    PriorityId           smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Priorities PRIMARY KEY,
    PriorityCode         VARCHAR(20) NOT NULL CONSTRAINT UQ_Priorities_Code UNIQUE,
    PriorityName         varchar(50) NOT NULL,
    SortOrder            SMALLINT NOT NULL,
    IsEnabled            boolean NOT NULL CONSTRAINT DF_Priorities_Enabled DEFAULT TRUE,
    CONSTRAINT UQ_Priorities_Order UNIQUE (SortOrder),
    CONSTRAINT CK_Priorities_Order CHECK (SortOrder >= 0)
);

CREATE TABLE work.Projects
(
    ProjectId            int GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Projects PRIMARY KEY,
    OrganizationId       INT NOT NULL,
    DepartmentId         INT NULL,
    ProjectCode          varchar(30) NOT NULL,
    ProjectName          varchar(150) NOT NULL,
    Description          varchar(2000) NOT NULL,
    OwnerUserId          INT NOT NULL,
    ProjectStatusId      SMALLINT NOT NULL,
    PriorityId           SMALLINT NOT NULL,
    StartDate            DATE NOT NULL,
    EndDate              DATE NOT NULL,
    CreatedByUserId      INT NOT NULL,
    CreationReason       varchar(1000) NULL,
    ActivatedAtUtc       timestamptz(0) NULL,
    ArchivedAtUtc        timestamptz(0) NULL,
    ArchivedByUserId     INT NULL,
    ArchiveReason        varchar(500) NULL,
    CreatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_Projects_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_Projects_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion           bigint NOT NULL DEFAULT 1,
    CONSTRAINT UQ_Projects_Organization_Code UNIQUE (OrganizationId, ProjectCode),
    CONSTRAINT CK_Projects_Name CHECK (char_length(btrim(ProjectName)) > 0),
    CONSTRAINT CK_Projects_Description CHECK (char_length(btrim(Description)) > 0),
    CONSTRAINT CK_Projects_Dates CHECK (EndDate >= StartDate),
    CONSTRAINT CK_Projects_Archive CHECK
            ((ArchivedAtUtc IS NULL AND ArchivedByUserId IS NULL) OR
             (ArchivedAtUtc IS NOT NULL AND ArchivedByUserId IS NOT NULL AND char_length(btrim(ArchiveReason)) > 0))
);

CREATE TABLE work.ProjectMembers
(
    ProjectMemberId      bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ProjectMembers PRIMARY KEY,
    ProjectId            INT NOT NULL,
    UserId               INT NOT NULL,
    MemberRoleCode       VARCHAR(30) NOT NULL CONSTRAINT DF_ProjectMembers_Role DEFAULT ('Member'),
    AddedByUserId        INT NOT NULL,
    JoinedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_ProjectMembers_Joined DEFAULT (CURRENT_TIMESTAMP),
    LeftAtUtc            timestamptz(0) NULL,
    RemovedByUserId      INT NULL,
    RemovalReason        varchar(500) NULL,
    CONSTRAINT CK_ProjectMembers_Role CHECK (MemberRoleCode IN ('Owner','TeamLead','Member','Reviewer','Observer')),
    CONSTRAINT CK_ProjectMembers_Left CHECK
            ((LeftAtUtc IS NULL AND RemovedByUserId IS NULL) OR
             (LeftAtUtc IS NOT NULL AND RemovedByUserId IS NOT NULL AND LeftAtUtc >= JoinedAtUtc))
);

CREATE TABLE work.ProjectReviewerDesignations
(
    ProjectReviewerId    bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ProjectReviewerDesignations PRIMARY KEY,
    ProjectId            INT NOT NULL,
    ReviewerUserId       INT NOT NULL,
    DesignatedByUserId   INT NOT NULL,
    StartsAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_ProjectReviewers_Start DEFAULT (CURRENT_TIMESTAMP),
    EndsAtUtc            timestamptz(0) NULL,
    CONSTRAINT CK_ProjectReviewers_Dates CHECK (EndsAtUtc IS NULL OR EndsAtUtc > StartsAtUtc)
);

CREATE TABLE work.ProjectMilestones
(
    MilestoneId          bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ProjectMilestones PRIMARY KEY,
    ProjectId            INT NOT NULL,
    MilestoneName        varchar(150) NOT NULL,
    Description          varchar(1000) NULL,
    DueDate              DATE NOT NULL,
    CompletedAtUtc       timestamptz(0) NULL,
    CreatedByUserId      INT NOT NULL,
    CreatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_Milestones_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_Milestones_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion           bigint NOT NULL DEFAULT 1,
    CONSTRAINT UQ_Milestones_Project_Name UNIQUE (ProjectId, MilestoneName),
    CONSTRAINT CK_Milestones_Name CHECK (char_length(btrim(MilestoneName)) > 0)
);

CREATE TABLE work.ProjectPolicies
(
    ProjectId                    INT CONSTRAINT PK_ProjectPolicies PRIMARY KEY,
    RequireAdminActivation       boolean NOT NULL CONSTRAINT DF_ProjectPolicies_Activation DEFAULT FALSE,
    RequireReviewCompletion      boolean NOT NULL CONSTRAINT DF_ProjectPolicies_Review DEFAULT TRUE,
    AllowLeadArchive             boolean NOT NULL CONSTRAINT DF_ProjectPolicies_LeadArchive DEFAULT FALSE,
    AllowLeadDeleteTasks         boolean NOT NULL CONSTRAINT DF_ProjectPolicies_LeadDelete DEFAULT FALSE,
    RequireEvidenceForReview     boolean NOT NULL CONSTRAINT DF_ProjectPolicies_Evidence DEFAULT FALSE,
    UpdatedByUserId              INT NOT NULL,
    UpdatedAtUtc                 timestamptz(0) NOT NULL CONSTRAINT DF_ProjectPolicies_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion                   bigint NOT NULL DEFAULT 1
);

CREATE TABLE work.Tasks
(
    TaskId                bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Tasks PRIMARY KEY,
    ProjectId             INT NOT NULL,
    ParentTaskId          BIGINT NULL,
    TaskNumber            INT NOT NULL,
    Title                 varchar(200) NOT NULL,
    Description           text NOT NULL,
    TaskStatusId          SMALLINT NOT NULL,
    PriorityId            SMALLINT NOT NULL,
    StartDate             DATE NOT NULL,
    DueDate               DATE NOT NULL,
    SortPosition          numeric(19,6) NOT NULL CONSTRAINT DF_Tasks_Position DEFAULT (0),
    CreatedByUserId       INT NOT NULL,
    DefaultReviewerUserId INT NULL,
    ActualStartedAtUtc    timestamptz(0) NULL,
    SubmittedAtUtc        timestamptz(0) NULL,
    CompletedAtUtc        timestamptz(0) NULL,
    CompletionSummary     varchar(2000) NULL,
    ArchivedAtUtc         timestamptz(0) NULL,
    ProjectArchivedAtUtc  timestamptz(0) NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_Tasks_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_Tasks_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion            bigint NOT NULL DEFAULT 1,
    CONSTRAINT UQ_Tasks_Project_Number UNIQUE (ProjectId, TaskNumber),
    CONSTRAINT CK_Tasks_Title CHECK (char_length(btrim(Title)) > 0),
    CONSTRAINT CK_Tasks_Description CHECK (char_length(btrim(Description)) > 0),
    CONSTRAINT CK_Tasks_Dates CHECK (DueDate >= StartDate),
    CONSTRAINT CK_Tasks_NoSelfParent CHECK (ParentTaskId IS NULL OR ParentTaskId <> TaskId),
    CONSTRAINT CK_Tasks_Completion CHECK
            ((CompletedAtUtc IS NULL AND CompletionSummary IS NULL) OR
             (CompletedAtUtc IS NOT NULL AND char_length(btrim(CompletionSummary)) > 0))
);

CREATE TABLE work.TaskAssignees
(
    TaskAssigneeId        bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_TaskAssignees PRIMARY KEY,
    TaskId                BIGINT NOT NULL,
    UserId                INT NOT NULL,
    AssignedByUserId      INT NOT NULL,
    AssignedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_TaskAssignees_Assigned DEFAULT (CURRENT_TIMESTAMP),
    UnassignedAtUtc       timestamptz(0) NULL,
    UnassignedByUserId    INT NULL,
    UnassignmentReason    varchar(500) NULL,
    CONSTRAINT CK_TaskAssignees_Unassigned CHECK
            ((UnassignedAtUtc IS NULL AND UnassignedByUserId IS NULL) OR
             (UnassignedAtUtc IS NOT NULL AND UnassignedByUserId IS NOT NULL AND UnassignedAtUtc >= AssignedAtUtc))
);

CREATE TABLE work.TaskAcceptanceCriteria
(
    AcceptanceCriterionId bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_TaskAcceptanceCriteria PRIMARY KEY,
    TaskId                 BIGINT NOT NULL,
    CriterionOrder         SMALLINT NOT NULL,
    CriterionText          varchar(1000) NOT NULL,
    IsSatisfied            boolean NOT NULL CONSTRAINT DF_AcceptanceCriteria_Satisfied DEFAULT FALSE,
    SatisfiedByUserId      INT NULL,
    SatisfiedAtUtc         timestamptz(0) NULL,
    CONSTRAINT UQ_AcceptanceCriteria_Order UNIQUE (TaskId, CriterionOrder),
    CONSTRAINT CK_AcceptanceCriteria_Text CHECK (char_length(btrim(CriterionText)) > 0),
    CONSTRAINT CK_AcceptanceCriteria_Satisfaction CHECK
            ((IsSatisfied IS FALSE AND SatisfiedByUserId IS NULL AND SatisfiedAtUtc IS NULL) OR
             (IsSatisfied IS TRUE AND SatisfiedByUserId IS NOT NULL AND SatisfiedAtUtc IS NOT NULL))
);

CREATE TABLE work.TaskDependencies
(
    TaskId                 BIGINT NOT NULL,
    DependsOnTaskId        BIGINT NOT NULL,
    DependencyType         VARCHAR(20) NOT NULL CONSTRAINT DF_TaskDependencies_Type DEFAULT ('FinishToStart'),
    CreatedByUserId        INT NOT NULL,
    CreatedAtUtc           timestamptz(0) NOT NULL CONSTRAINT DF_TaskDependencies_Created DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT PK_TaskDependencies PRIMARY KEY (TaskId, DependsOnTaskId),
    CONSTRAINT CK_TaskDependencies_NoSelf CHECK (TaskId <> DependsOnTaskId),
    CONSTRAINT CK_TaskDependencies_Type CHECK (DependencyType IN ('FinishToStart','StartToStart','FinishToFinish','StartToFinish'))
);

CREATE TABLE work.TaskStatusHistory
(
    TaskStatusHistoryId    bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_TaskStatusHistory PRIMARY KEY,
    TaskId                 BIGINT NOT NULL,
    FromTaskStatusId       SMALLINT NULL,
    ToTaskStatusId         SMALLINT NOT NULL,
    ChangedByUserId        INT NOT NULL,
    ProgressNote           varchar(2000) NULL,
    WorkSummary            varchar(2000) NULL,
    AssistanceRequired     varchar(1000) NULL,
    ChangedAtUtc           timestamptz(0) NOT NULL CONSTRAINT DF_TaskStatusHistory_Changed DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT CK_TaskStatusHistory_Changed CHECK (FromTaskStatusId IS NULL OR FromTaskStatusId <> ToTaskStatusId)
);

CREATE TABLE work.TaskBlockers
(
    TaskBlockerId          bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_TaskBlockers PRIMARY KEY,
    TaskId                 BIGINT NOT NULL,
    ReportedByUserId       INT NOT NULL,
    BlockerDescription     varchar(2000) NOT NULL,
    AssistanceRequired     varchar(1000) NOT NULL,
    ReportedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_TaskBlockers_Reported DEFAULT (CURRENT_TIMESTAMP),
    ResolvedByUserId       INT NULL,
    ResolutionNote         varchar(2000) NULL,
    ResolvedAtUtc          timestamptz(0) NULL,
    CONSTRAINT CK_TaskBlockers_Description CHECK (char_length(btrim(BlockerDescription)) > 0),
    CONSTRAINT CK_TaskBlockers_Assistance CHECK (char_length(btrim(AssistanceRequired)) > 0),
    CONSTRAINT CK_TaskBlockers_Resolution CHECK
            ((ResolvedAtUtc IS NULL AND ResolvedByUserId IS NULL AND ResolutionNote IS NULL) OR
             (ResolvedAtUtc IS NOT NULL AND ResolvedByUserId IS NOT NULL AND char_length(btrim(ResolutionNote)) > 0))
);

CREATE TABLE work.ChangeRequestTypes
(
    ChangeRequestTypeId   smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ChangeRequestTypes PRIMARY KEY,
    TypeCode              VARCHAR(40) NOT NULL CONSTRAINT UQ_ChangeRequestTypes_Code UNIQUE,
    TypeName              varchar(100) NOT NULL,
    IsEnabled             boolean NOT NULL CONSTRAINT DF_ChangeRequestTypes_Enabled DEFAULT TRUE
);

CREATE TABLE work.TaskChangeRequests
(
    ChangeRequestId       bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_TaskChangeRequests PRIMARY KEY,
    TaskId                BIGINT NOT NULL,
    ChangeRequestTypeId   SMALLINT NOT NULL,
    RequestedByUserId     INT NOT NULL,
    RequestReason         varchar(1000) NOT NULL,
    RequestStatus         VARCHAR(30) NOT NULL CONSTRAINT DF_ChangeRequests_Status DEFAULT ('Draft'),
    AssignedReviewerUserId INT NULL,
    SubmittedAtUtc        timestamptz(0) NULL,
    DecisionAtUtc         timestamptz(0) NULL,
    ExpiresAtUtc          timestamptz(0) NULL,
    CancelledAtUtc        timestamptz(0) NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_ChangeRequests_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_ChangeRequests_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion            bigint NOT NULL DEFAULT 1,
    CONSTRAINT CK_ChangeRequests_Reason CHECK (char_length(btrim(RequestReason)) > 0),
    CONSTRAINT CK_ChangeRequests_Status CHECK
            (RequestStatus IN ('Draft','Pending','ClarificationRequested','Approved','Rejected','Cancelled','Expired','Overridden')),
    CONSTRAINT CK_ChangeRequests_NoSelfReview CHECK
            (AssignedReviewerUserId IS NULL OR AssignedReviewerUserId <> RequestedByUserId),
    CONSTRAINT CK_ChangeRequests_Expiry CHECK (ExpiresAtUtc IS NULL OR SubmittedAtUtc IS NULL OR ExpiresAtUtc > SubmittedAtUtc)
);

CREATE TABLE work.TaskChangeRequestItems
(
    ChangeRequestItemId   bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_TaskChangeRequestItems PRIMARY KEY,
    ChangeRequestId       BIGINT NOT NULL,
    FieldCode             VARCHAR(50) NOT NULL,
    OldValueJson          text NULL,
    ProposedValueJson     text NULL,
    CONSTRAINT UQ_ChangeRequestItems_Field UNIQUE (ChangeRequestId, FieldCode),
    CONSTRAINT CK_ChangeRequestItems_Field CHECK (char_length(btrim(FieldCode)) > 0),
    CONSTRAINT CK_ChangeRequestItems_OldJson CHECK (OldValueJson IS NULL OR config.is_valid_json(OldValueJson)),
    CONSTRAINT CK_ChangeRequestItems_NewJson CHECK (ProposedValueJson IS NULL OR config.is_valid_json(ProposedValueJson)),
    CONSTRAINT CK_ChangeRequestItems_Different CHECK
            (COALESCE(OldValueJson, 'null') <> COALESCE(ProposedValueJson, 'null'))
);

CREATE TABLE work.ChangeRequestReviews
(
    ChangeRequestReviewId bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ChangeRequestReviews PRIMARY KEY,
    ChangeRequestId       BIGINT NOT NULL,
    ReviewerUserId        INT NOT NULL,
    ReviewAction          VARCHAR(30) NOT NULL,
    ReviewNote            varchar(2000) NULL,
    ReviewerRoleCode      VARCHAR(40) NOT NULL,
    ReviewedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_ChangeRequestReviews_Reviewed DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT CK_ChangeRequestReviews_Action CHECK
            (ReviewAction IN ('ClarificationRequested','Approved','Rejected','Overridden')),
    CONSTRAINT CK_ChangeRequestReviews_OverrideNote CHECK
            (ReviewAction <> 'Overridden' OR char_length(btrim(ReviewNote)) > 0)
);
