-- Tables owned by the collab schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE collab.StoredFiles
(
    FileId                bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_StoredFiles PRIMARY KEY,
    OrganizationId        INT NOT NULL,
    UploadedByUserId      INT NOT NULL,
    OriginalFileName      varchar(255) NOT NULL,
    StorageObjectKey      varchar(500) NOT NULL,
    MimeType              varchar(150) NOT NULL,
    FileExtension         varchar(20) NULL,
    SizeBytes             BIGINT NOT NULL,
    Sha256Hash            bytea NOT NULL,
    ScanStatus            VARCHAR(20) NOT NULL CONSTRAINT DF_StoredFiles_Scan DEFAULT ('Pending'),
    IsDeleted             boolean NOT NULL CONSTRAINT DF_StoredFiles_Deleted DEFAULT FALSE,
    UploadedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_StoredFiles_Uploaded DEFAULT (CURRENT_TIMESTAMP),
    DeletedAtUtc          timestamptz(0) NULL,
    CONSTRAINT UQ_StoredFiles_ObjectKey UNIQUE (StorageObjectKey),
    CONSTRAINT CK_StoredFiles_Name CHECK (char_length(btrim(OriginalFileName)) > 0),
    CONSTRAINT CK_StoredFiles_Size CHECK (SizeBytes > 0),
    CONSTRAINT CK_StoredFiles_Scan CHECK (ScanStatus IN ('Pending','Clean','Rejected','Failed')),
    CONSTRAINT CK_StoredFiles_Deleted CHECK ((IsDeleted IS FALSE AND DeletedAtUtc IS NULL) OR (IsDeleted IS TRUE AND DeletedAtUtc IS NOT NULL))
);

CREATE TABLE collab.DiscussionThreads
(
    ThreadId              bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_DiscussionThreads PRIMARY KEY,
    OrganizationId        INT NOT NULL,
    ThreadType            VARCHAR(30) NOT NULL,
    Subject               varchar(200) NULL,
    ProjectId             INT NULL,
    TaskId                BIGINT NULL,
    ChangeRequestId       BIGINT NULL,
    AttendanceRecordId    BIGINT NULL,
    AttendanceCorrectionId BIGINT NULL,
    LeaveRequestId        BIGINT NULL,
    ReportRunId           BIGINT NULL,
    CreatedByUserId       INT NOT NULL,
    IsResolved            boolean NOT NULL CONSTRAINT DF_DiscussionThreads_Resolved DEFAULT FALSE,
    ResolvedByUserId      INT NULL,
    ResolvedAtUtc         timestamptz(0) NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_DiscussionThreads_Created DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT CK_DiscussionThreads_Type CHECK
            (ThreadType IN ('Project','Task','ChangeRequest','Attendance','AttendanceCorrection','Leave','Report')),
    CONSTRAINT CK_DiscussionThreads_OneParent CHECK
            ((CASE WHEN ProjectId IS NULL THEN 0 ELSE 1 END) +
             (CASE WHEN TaskId IS NULL THEN 0 ELSE 1 END) +
             (CASE WHEN ChangeRequestId IS NULL THEN 0 ELSE 1 END) +
             (CASE WHEN AttendanceRecordId IS NULL THEN 0 ELSE 1 END) +
             (CASE WHEN AttendanceCorrectionId IS NULL THEN 0 ELSE 1 END) +
             (CASE WHEN LeaveRequestId IS NULL THEN 0 ELSE 1 END) +
             (CASE WHEN ReportRunId IS NULL THEN 0 ELSE 1 END) = 1),
    CONSTRAINT CK_DiscussionThreads_Resolution CHECK
            ((IsResolved IS FALSE AND ResolvedByUserId IS NULL AND ResolvedAtUtc IS NULL) OR
             (IsResolved IS TRUE AND ResolvedByUserId IS NOT NULL AND ResolvedAtUtc IS NOT NULL))
);

CREATE TABLE collab.Comments
(
    CommentId             bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Comments PRIMARY KEY,
    ThreadId              BIGINT NOT NULL,
    ParentCommentId       BIGINT NULL,
    AuthorUserId          INT NOT NULL,
    CommentKind           VARCHAR(30) NOT NULL CONSTRAINT DF_Comments_Kind DEFAULT ('General'),
    CommentText           text NOT NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_Comments_Created DEFAULT (CURRENT_TIMESTAMP),
    EditedAtUtc           timestamptz(0) NULL,
    DeletedAtUtc          timestamptz(0) NULL,
    RowVersion            bigint NOT NULL DEFAULT 1,
    CONSTRAINT CK_Comments_Kind CHECK
            (CommentKind IN ('General','Progress','Blocker','Review','CorrectionRequest','ClarificationRequest','Decision')),
    CONSTRAINT CK_Comments_Text CHECK (char_length(btrim(CommentText)) > 0),
    CONSTRAINT CK_Comments_NoSelfParent CHECK (ParentCommentId IS NULL OR ParentCommentId <> CommentId)
);

CREATE TABLE collab.CommentMentions
(
    CommentId             BIGINT NOT NULL,
    MentionedUserId       INT NOT NULL,
    CONSTRAINT PK_CommentMentions PRIMARY KEY (CommentId, MentionedUserId)
);

CREATE TABLE collab.ProjectFiles
(
    ProjectId             INT NOT NULL,
    FileId                BIGINT NOT NULL,
    AddedByUserId         INT NOT NULL,
    AddedAtUtc            timestamptz(0) NOT NULL CONSTRAINT DF_ProjectFiles_Added DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT PK_ProjectFiles PRIMARY KEY (ProjectId, FileId)
);

CREATE TABLE collab.TaskFiles
(
    TaskId                BIGINT NOT NULL,
    FileId                BIGINT NOT NULL,
    FilePurpose           VARCHAR(30) NOT NULL CONSTRAINT DF_TaskFiles_Purpose DEFAULT ('Attachment'),
    AddedByUserId         INT NOT NULL,
    AddedAtUtc            timestamptz(0) NOT NULL CONSTRAINT DF_TaskFiles_Added DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT PK_TaskFiles PRIMARY KEY (TaskId, FileId),
    CONSTRAINT CK_TaskFiles_Purpose CHECK (FilePurpose IN ('Attachment','CompletionEvidence','ReviewEvidence'))
);

CREATE TABLE collab.CommentFiles
(
    CommentId             BIGINT NOT NULL,
    FileId                BIGINT NOT NULL,
    CONSTRAINT PK_CommentFiles PRIMARY KEY (CommentId, FileId)
);

CREATE TABLE collab.LeaveRequestFiles
(
    LeaveRequestId        BIGINT NOT NULL,
    FileId                BIGINT NOT NULL,
    CONSTRAINT PK_LeaveRequestFiles PRIMARY KEY (LeaveRequestId, FileId)
);
