-- Tables owned by the hr schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE hr.WorkSchedules
(
    WorkScheduleId        int GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_WorkSchedules PRIMARY KEY,
    OrganizationId        INT NOT NULL,
    ScheduleName          varchar(100) NOT NULL,
    EffectiveFrom         DATE NOT NULL,
    EffectiveTo           DATE NULL,
    GraceMinutes          SMALLINT NOT NULL CONSTRAINT DF_WorkSchedules_Grace DEFAULT (0),
    IsDefault             boolean NOT NULL CONSTRAINT DF_WorkSchedules_Default DEFAULT FALSE,
    CreatedByUserId       INT NOT NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_WorkSchedules_Created DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT UQ_WorkSchedules_NameFrom UNIQUE (OrganizationId, ScheduleName, EffectiveFrom),
    CONSTRAINT CK_WorkSchedules_Dates CHECK (EffectiveTo IS NULL OR EffectiveTo >= EffectiveFrom),
    CONSTRAINT CK_WorkSchedules_Grace CHECK (GraceMinutes >= 0)
);

CREATE TABLE hr.WorkScheduleDays
(
    WorkScheduleId        INT NOT NULL,
    IsoWeekday            smallint NOT NULL,
    IsWorkingDay          boolean NOT NULL,
    StartTime             TIME(0) NULL,
    EndTime               TIME(0) NULL,
    BreakMinutes          SMALLINT NOT NULL CONSTRAINT DF_WorkScheduleDays_Break DEFAULT (0),
    CONSTRAINT PK_WorkScheduleDays PRIMARY KEY (WorkScheduleId, IsoWeekday),
    CONSTRAINT CK_WorkScheduleDays_Weekday CHECK (IsoWeekday BETWEEN 1 AND 7),
    CONSTRAINT CK_WorkScheduleDays_Times CHECK
            ((IsWorkingDay IS FALSE AND StartTime IS NULL AND EndTime IS NULL) OR
             (IsWorkingDay IS TRUE AND StartTime IS NOT NULL AND EndTime IS NOT NULL AND EndTime > StartTime)),
    CONSTRAINT CK_WorkScheduleDays_Break CHECK (BreakMinutes >= 0)
);

CREATE TABLE hr.UserWorkScheduleAssignments
(
    UserWorkScheduleAssignmentId bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_UserWorkScheduleAssignments PRIMARY KEY,
    UserId               INT NOT NULL,
    WorkScheduleId       INT NOT NULL,
    EffectiveFrom        DATE NOT NULL,
    EffectiveTo          DATE NULL,
    AssignedByUserId     INT NOT NULL,
    CONSTRAINT UQ_UserWorkSchedules_UserFrom UNIQUE (UserId, EffectiveFrom),
    CONSTRAINT CK_UserWorkSchedules_Dates CHECK (EffectiveTo IS NULL OR EffectiveTo >= EffectiveFrom)
);

CREATE TABLE hr.Holidays
(
    HolidayId             int GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Holidays PRIMARY KEY,
    OrganizationId        INT NOT NULL,
    DepartmentId          INT NULL,
    HolidayName           varchar(120) NOT NULL,
    HolidayDate           DATE NOT NULL,
    IsRecurringAnnual     boolean NOT NULL CONSTRAINT DF_Holidays_Recurring DEFAULT FALSE,
    CreatedByUserId       INT NOT NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_Holidays_Created DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT UQ_Holidays_ScopeDateName UNIQUE NULLS NOT DISTINCT (OrganizationId, DepartmentId, HolidayDate, HolidayName),
    CONSTRAINT CK_Holidays_Name CHECK (char_length(btrim(HolidayName)) > 0)
);

CREATE TABLE hr.AttendanceStatuses
(
    AttendanceStatusId    smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_AttendanceStatuses PRIMARY KEY,
    StatusCode            VARCHAR(30) NOT NULL CONSTRAINT UQ_AttendanceStatuses_Code UNIQUE,
    StatusName            varchar(80) NOT NULL,
    CountsAsPresent       boolean NOT NULL,
    IsEnabled             boolean NOT NULL CONSTRAINT DF_AttendanceStatuses_Enabled DEFAULT TRUE
);

CREATE TABLE hr.AttendanceRecords
(
    AttendanceRecordId    bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_AttendanceRecords PRIMARY KEY,
    UserId                INT NOT NULL,
    WorkDate              DATE NOT NULL,
    WorkScheduleId        INT NULL,
    AttendanceStatusId    SMALLINT NOT NULL,
    ScheduledStartTime    TIME(0) NULL,
    ScheduledEndTime      TIME(0) NULL,
    ActualCheckInAtUtc    timestamptz(0) NULL,
    ActualCheckOutAtUtc   timestamptz(0) NULL,
    WorkingMinutes        INT NULL,
    LateMinutes           INT NOT NULL CONSTRAINT DF_AttendanceRecords_Late DEFAULT (0),
    EarlyDepartureMinutes INT NOT NULL CONSTRAINT DF_AttendanceRecords_Early DEFAULT (0),
    SourceCode            VARCHAR(20) NOT NULL CONSTRAINT DF_AttendanceRecords_Source DEFAULT ('SelfService'),
    IsLocked              boolean NOT NULL CONSTRAINT DF_AttendanceRecords_Locked DEFAULT FALSE,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_AttendanceRecords_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_AttendanceRecords_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion            bigint NOT NULL DEFAULT 1,
    CONSTRAINT UQ_AttendanceRecords_UserDate UNIQUE (UserId, WorkDate),
    CONSTRAINT CK_AttendanceRecords_CheckTimes CHECK
            (ActualCheckOutAtUtc IS NULL OR (ActualCheckInAtUtc IS NOT NULL AND ActualCheckOutAtUtc > ActualCheckInAtUtc)),
    CONSTRAINT CK_AttendanceRecords_Minutes CHECK
            ((WorkingMinutes IS NULL OR WorkingMinutes >= 0) AND LateMinutes >= 0 AND EarlyDepartureMinutes >= 0),
    CONSTRAINT CK_AttendanceRecords_Source CHECK (SourceCode IN ('SelfService','HRCorrection','Import','System'))
);

CREATE TABLE hr.AttendancePunches
(
    AttendancePunchId     bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_AttendancePunches PRIMARY KEY,
    AttendanceRecordId    BIGINT NOT NULL,
    PunchType             VARCHAR(10) NOT NULL,
    PunchedAtUtc          timestamptz(0) NOT NULL,
    RecordedByUserId      INT NOT NULL,
    SourceCode            VARCHAR(20) NOT NULL CONSTRAINT DF_AttendancePunches_Source DEFAULT ('SelfService'),
    DeviceInfo            varchar(300) NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_AttendancePunches_Created DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT CK_AttendancePunches_Type CHECK (PunchType IN ('CheckIn','CheckOut')),
    CONSTRAINT CK_AttendancePunches_Source CHECK (SourceCode IN ('SelfService','HRCorrection','Import','System'))
);

CREATE TABLE hr.AttendanceCorrectionRequests
(
    AttendanceCorrectionId bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_AttendanceCorrections PRIMARY KEY,
    AttendanceRecordId    BIGINT NOT NULL,
    RequestedByUserId     INT NOT NULL,
    Reason                varchar(1000) NOT NULL,
    RequestStatus         VARCHAR(30) NOT NULL CONSTRAINT DF_AttendanceCorrections_Status DEFAULT ('Pending'),
    AssignedReviewerUserId INT NULL,
    SubmittedAtUtc        timestamptz(0) NOT NULL CONSTRAINT DF_AttendanceCorrections_Submitted DEFAULT (CURRENT_TIMESTAMP),
    DecisionAtUtc         timestamptz(0) NULL,
    RowVersion            bigint NOT NULL DEFAULT 1,
    CONSTRAINT CK_AttendanceCorrections_Reason CHECK (char_length(btrim(Reason)) > 0),
    CONSTRAINT CK_AttendanceCorrections_Status CHECK
            (RequestStatus IN ('Pending','ClarificationRequested','Approved','Rejected','Cancelled','Escalated')),
    CONSTRAINT CK_AttendanceCorrections_NoSelfReview CHECK
            (AssignedReviewerUserId IS NULL OR AssignedReviewerUserId <> RequestedByUserId)
);

CREATE TABLE hr.AttendanceCorrectionItems
(
    AttendanceCorrectionItemId bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_AttendanceCorrectionItems PRIMARY KEY,
    AttendanceCorrectionId BIGINT NOT NULL,
    FieldCode             VARCHAR(40) NOT NULL,
    OriginalValue         varchar(100) NULL,
    RequestedValue        varchar(100) NULL,
    CONSTRAINT UQ_AttendanceCorrectionItems_Field UNIQUE (AttendanceCorrectionId, FieldCode),
    CONSTRAINT CK_AttendanceCorrectionItems_Field CHECK
            (FieldCode IN ('CheckIn','CheckOut','Status','WorkingMinutes')),
    CONSTRAINT CK_AttendanceCorrectionItems_Different CHECK
            (COALESCE(OriginalValue, '') <> COALESCE(RequestedValue, ''))
);

CREATE TABLE hr.AttendanceCorrectionReviews
(
    AttendanceCorrectionReviewId bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_AttendanceCorrectionReviews PRIMARY KEY,
    AttendanceCorrectionId BIGINT NOT NULL,
    ReviewerUserId        INT NOT NULL,
    DecisionCode          VARCHAR(30) NOT NULL,
    DecisionNote          varchar(2000) NULL,
    ReviewedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_AttendanceCorrectionReviews_Reviewed DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT CK_AttendanceCorrectionReviews_Decision CHECK
            (DecisionCode IN ('ClarificationRequested','Approved','Rejected','Escalated','Overridden'))
);

CREATE TABLE hr.LeaveTypes
(
    LeaveTypeId           smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_LeaveTypes PRIMARY KEY,
    OrganizationId        INT NOT NULL,
    LeaveTypeCode         VARCHAR(30) NOT NULL,
    LeaveTypeName         varchar(80) NOT NULL,
    RequiresAttachment    boolean NOT NULL CONSTRAINT DF_LeaveTypes_Attachment DEFAULT FALSE,
    IsPaid                boolean NOT NULL CONSTRAINT DF_LeaveTypes_Paid DEFAULT TRUE,
    IsEnabled             boolean NOT NULL CONSTRAINT DF_LeaveTypes_Enabled DEFAULT TRUE,
    CONSTRAINT UQ_LeaveTypes_Organization_Code UNIQUE (OrganizationId, LeaveTypeCode)
);

CREATE TABLE hr.LeaveRequests
(
    LeaveRequestId        bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_LeaveRequests PRIMARY KEY,
    UserId                INT NOT NULL,
    LeaveTypeId           SMALLINT NOT NULL,
    StartDate             DATE NOT NULL,
    EndDate               DATE NOT NULL,
    IsPartialDay          boolean NOT NULL CONSTRAINT DF_LeaveRequests_Partial DEFAULT FALSE,
    PartialStartTime      TIME(0) NULL,
    PartialEndTime        TIME(0) NULL,
    Reason                varchar(1000) NOT NULL,
    RequestStatus         VARCHAR(30) NOT NULL CONSTRAINT DF_LeaveRequests_Status DEFAULT ('Pending'),
    AssignedReviewerUserId INT NULL,
    SubmittedAtUtc        timestamptz(0) NOT NULL CONSTRAINT DF_LeaveRequests_Submitted DEFAULT (CURRENT_TIMESTAMP),
    DecisionAtUtc         timestamptz(0) NULL,
    CancelledAtUtc        timestamptz(0) NULL,
    RowVersion            bigint NOT NULL DEFAULT 1,
    CONSTRAINT CK_LeaveRequests_Dates CHECK (EndDate >= StartDate),
    CONSTRAINT CK_LeaveRequests_Reason CHECK (char_length(btrim(Reason)) > 0),
    CONSTRAINT CK_LeaveRequests_Status CHECK
            (RequestStatus IN ('Pending','ClarificationRequested','Approved','Rejected','Cancelled','Escalated')),
    CONSTRAINT CK_LeaveRequests_NoSelfReview CHECK
            (AssignedReviewerUserId IS NULL OR AssignedReviewerUserId <> UserId),
    CONSTRAINT CK_LeaveRequests_Partial CHECK
            ((IsPartialDay IS FALSE AND PartialStartTime IS NULL AND PartialEndTime IS NULL) OR
             (IsPartialDay IS TRUE AND StartDate = EndDate AND PartialStartTime IS NOT NULL
              AND PartialEndTime IS NOT NULL AND PartialEndTime > PartialStartTime))
);

CREATE TABLE hr.LeaveRequestReviews
(
    LeaveRequestReviewId  bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_LeaveRequestReviews PRIMARY KEY,
    LeaveRequestId        BIGINT NOT NULL,
    ReviewerUserId        INT NOT NULL,
    DecisionCode          VARCHAR(30) NOT NULL,
    DecisionNote          varchar(2000) NULL,
    ReviewedAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_LeaveReviews_Reviewed DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT CK_LeaveReviews_Decision CHECK
            (DecisionCode IN ('ClarificationRequested','Approved','Rejected','Escalated','Overridden'))
);
