-- Tables owned by the calendar schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE calendar.EventTypes
(
    EventTypeId           smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_EventTypes PRIMARY KEY,
    EventTypeCode         VARCHAR(30) NOT NULL CONSTRAINT UQ_EventTypes_Code UNIQUE,
    EventTypeName         varchar(80) NOT NULL,
    IconName              varchar(80) NULL,
    IsEnabled             boolean NOT NULL CONSTRAINT DF_EventTypes_Enabled DEFAULT TRUE
);

CREATE TABLE calendar.Events
(
    EventId               bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Events PRIMARY KEY,
    OrganizationId        INT NOT NULL,
    EventTypeId           SMALLINT NOT NULL,
    ProjectId             INT NULL,
    Title                 varchar(200) NOT NULL,
    Description           varchar(2000) NULL,
    Location              varchar(300) NULL,
    StartsAtUtc           timestamptz(0) NOT NULL,
    EndsAtUtc             timestamptz(0) NOT NULL,
    IsAllDay              boolean NOT NULL CONSTRAINT DF_Events_AllDay DEFAULT FALSE,
    VisibilityCode        VARCHAR(20) NOT NULL CONSTRAINT DF_Events_Visibility DEFAULT ('Organization'),
    CreatedByUserId       INT NOT NULL,
    CancelledAtUtc        timestamptz(0) NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_Events_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_Events_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion            bigint NOT NULL DEFAULT 1,
    CONSTRAINT CK_Events_Title CHECK (char_length(btrim(Title)) > 0),
    CONSTRAINT CK_Events_Dates CHECK (EndsAtUtc > StartsAtUtc),
    CONSTRAINT CK_Events_Visibility CHECK (VisibilityCode IN ('Organization','Project','Attendees','Private'))
);

CREATE TABLE calendar.EventAttendees
(
    EventId               BIGINT NOT NULL,
    UserId                INT NOT NULL,
    AttendanceRole        VARCHAR(20) NOT NULL CONSTRAINT DF_EventAttendees_Role DEFAULT ('Required'),
    ResponseStatus        VARCHAR(20) NOT NULL CONSTRAINT DF_EventAttendees_Response DEFAULT ('Pending'),
    RespondedAtUtc        timestamptz(0) NULL,
    CONSTRAINT PK_EventAttendees PRIMARY KEY (EventId, UserId),
    CONSTRAINT CK_EventAttendees_Role CHECK (AttendanceRole IN ('Organizer','Required','Optional')),
    CONSTRAINT CK_EventAttendees_Response CHECK (ResponseStatus IN ('Pending','Accepted','Declined','Tentative'))
);
