-- Tables owned by the reporting schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE reporting.ReportDefinitions
(
    ReportDefinitionId    smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ReportDefinitions PRIMARY KEY,
    ReportCode            VARCHAR(50) NOT NULL CONSTRAINT UQ_ReportDefinitions_Code UNIQUE,
    ReportName            varchar(120) NOT NULL,
    ReportCategory        VARCHAR(30) NOT NULL,
    RequiredPermissionCode VARCHAR(80) NOT NULL,
    IsEnabled             boolean NOT NULL CONSTRAINT DF_ReportDefinitions_Enabled DEFAULT TRUE,
    CONSTRAINT CK_ReportDefinitions_Category CHECK
            (ReportCategory IN ('Personal','Project','Team','Organization','Attendance'))
);

CREATE TABLE reporting.SavedReports
(
    SavedReportId         bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_SavedReports PRIMARY KEY,
    ReportDefinitionId    SMALLINT NOT NULL,
    OwnerUserId           INT NOT NULL,
    SavedReportName       varchar(150) NOT NULL,
    FilterJson            text NOT NULL,
    IsScheduled           boolean NOT NULL CONSTRAINT DF_SavedReports_Scheduled DEFAULT FALSE,
    ScheduleExpression    varchar(200) NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_SavedReports_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_SavedReports_Updated DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT UQ_SavedReports_OwnerName UNIQUE (OwnerUserId, SavedReportName),
    CONSTRAINT CK_SavedReports_FilterJson CHECK (config.is_valid_json(FilterJson)),
    CONSTRAINT CK_SavedReports_Schedule CHECK
            ((IsScheduled IS FALSE AND ScheduleExpression IS NULL) OR
             (IsScheduled IS TRUE AND char_length(btrim(ScheduleExpression)) > 0))
);

CREATE TABLE reporting.ReportRuns
(
    ReportRunId           bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ReportRuns PRIMARY KEY,
    ReportDefinitionId    SMALLINT NOT NULL,
    SavedReportId         BIGINT NULL,
    RequestedByUserId     INT NOT NULL,
    FilterSnapshotJson    text NOT NULL,
    RunStatus             VARCHAR(20) NOT NULL CONSTRAINT DF_ReportRuns_Status DEFAULT ('Queued'),
    StartedAtUtc          timestamptz(0) NULL,
    CompletedAtUtc        timestamptz(0) NULL,
    FailureMessage        varchar(2000) NULL,
    RequestedAtUtc        timestamptz(0) NOT NULL CONSTRAINT DF_ReportRuns_Requested DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT CK_ReportRuns_FilterJson CHECK (config.is_valid_json(FilterSnapshotJson)),
    CONSTRAINT CK_ReportRuns_Status CHECK (RunStatus IN ('Queued','Running','Succeeded','Failed','Cancelled'))
);

CREATE TABLE reporting.ReportExports
(
    ReportExportId        bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ReportExports PRIMARY KEY,
    ReportRunId           BIGINT NOT NULL,
    FileId                BIGINT NOT NULL,
    ExportFormat          VARCHAR(10) NOT NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_ReportExports_Created DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT UQ_ReportExports_RunFormat UNIQUE (ReportRunId, ExportFormat),
    CONSTRAINT CK_ReportExports_Format CHECK (ExportFormat IN ('CSV','PDF','XLSX'))
);
