-- Tables owned by the ai schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE ai.PromptOutputTypes
(
    PromptOutputTypeId    smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_PromptOutputTypes PRIMARY KEY,
    OutputTypeCode        VARCHAR(40) NOT NULL CONSTRAINT UQ_PromptOutputTypes_Code UNIQUE,
    OutputTypeName        varchar(100) NOT NULL,
    RequiresProject       boolean NOT NULL,
    RequiresTask          boolean NOT NULL,
    IsEnabled             boolean NOT NULL CONSTRAINT DF_PromptOutputTypes_Enabled DEFAULT TRUE
);

CREATE TABLE ai.PromptGenerations
(
    PromptGenerationId    bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_PromptGenerations PRIMARY KEY,
    UserId                INT NOT NULL,
    ProjectId             INT NULL,
    TaskId                BIGINT NULL,
    PromptOutputTypeId    SMALLINT NOT NULL,
    StyleCode             VARCHAR(30) NOT NULL,
    AdditionalDescription varchar(4000) NULL,
    ContextSnapshotJson   text NOT NULL,
    PromptText            text NOT NULL,
    GeneratedContent      text NULL,
    EditedContent         text NULL,
    GenerationStatus      VARCHAR(20) NOT NULL CONSTRAINT DF_PromptGenerations_Status DEFAULT ('Queued'),
    ModelIdentifier       varchar(100) NULL,
    ParentGenerationId    BIGINT NULL,
    IsSaved               boolean NOT NULL CONSTRAINT DF_PromptGenerations_Saved DEFAULT FALSE,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_PromptGenerations_Created DEFAULT (CURRENT_TIMESTAMP),
    CompletedAtUtc        timestamptz(0) NULL,
    CONSTRAINT CK_PromptGenerations_Style CHECK
            (StyleCode IN ('Default','Short','Long','Technical','Beginner','Checklist','StepByStep')),
    CONSTRAINT CK_PromptGenerations_ContextJson CHECK (config.is_valid_json(ContextSnapshotJson)),
    CONSTRAINT CK_PromptGenerations_Status CHECK (GenerationStatus IN ('Queued','Running','Succeeded','Failed','Cancelled'))
);
