-- Tables owned by the ai schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE ai.PromptOutputTypes
(
    PromptOutputTypeId    smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_PromptOutputTypes PRIMARY KEY,
    OutputTypeCode        VARCHAR(40) NOT NULL CONSTRAINT UQ_PromptOutputTypes_Code UNIQUE,
    OutputTypeName        varchar(100) NOT NULL,
    RequiresProject       boolean NOT NULL,
    RequiresTask          boolean NOT NULL,
    IsEnabled             boolean NOT NULL CONSTRAINT DF_PromptOutputTypes_Enabled DEFAULT TRUE
);

CREATE TABLE ai.PromptGenerations
(
    PromptGenerationId    bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_PromptGenerations PRIMARY KEY,
    UserId                INT NOT NULL,
    ProjectId             INT NULL,
    TaskId                BIGINT NULL,
    PromptOutputTypeId    SMALLINT NOT NULL,
    StyleCode             VARCHAR(30) NOT NULL,
    AdditionalDescription varchar(4000) NULL,
    ContextSnapshotJson   text NOT NULL,
    PromptText            text NOT NULL,
    GeneratedContent      text NULL,
    EditedContent         text NULL,
    GenerationStatus      VARCHAR(20) NOT NULL CONSTRAINT DF_PromptGenerations_Status DEFAULT ('Queued'),
    ModelIdentifier       varchar(100) NULL,
    ParentGenerationId    BIGINT NULL,
    IsSaved               boolean NOT NULL CONSTRAINT DF_PromptGenerations_Saved DEFAULT FALSE,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_PromptGenerations_Created DEFAULT (CURRENT_TIMESTAMP),
    CompletedAtUtc        timestamptz(0) NULL,
    CONSTRAINT CK_PromptGenerations_Style CHECK
            (StyleCode IN ('Default','Short','Long','Technical','Beginner','Checklist','StepByStep')),
    CONSTRAINT CK_PromptGenerations_ContextJson CHECK (config.is_valid_json(ContextSnapshotJson)),
    CONSTRAINT CK_PromptGenerations_Status CHECK (GenerationStatus IN ('Queued','Running','Succeeded','Failed','Cancelled'))
);

-- The AI Assistant prompt library: prompts a user saves from the Generate tab. This table
-- (plus ai.PromptVersions below) is what makes saved prompts survive page reloads and backend
-- restarts, unlike the purely in-memory promptStore that preceded it.
CREATE TABLE ai.PromptLibraries
(
    PromptLibraryId        bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_PromptLibraries PRIMARY KEY,
    UserId                 INT NOT NULL,
    ProjectId              INT NULL,
    TaskId                 BIGINT NULL,
    CategoryCode           VARCHAR(40) NOT NULL,
    Title                  VARCHAR(200) NOT NULL,
    StyleCode              VARCHAR(30) NOT NULL CONSTRAINT DF_PromptLibraries_Style DEFAULT ('Default'),
    AdditionalInstructions TEXT NULL,
    IsArchived             boolean NOT NULL CONSTRAINT DF_PromptLibraries_Archived DEFAULT FALSE,
    CreatedAtUtc           timestamptz(0) NOT NULL CONSTRAINT DF_PromptLibraries_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc           timestamptz(0) NOT NULL CONSTRAINT DF_PromptLibraries_Updated DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE ai.PromptVersions
(
    PromptVersionId    bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_PromptVersions PRIMARY KEY,
    PromptLibraryId    bigint NOT NULL,
    VersionNumber      INT NOT NULL,
    Content            TEXT NOT NULL,
    IsAiGenerated      boolean NOT NULL CONSTRAINT DF_PromptVersions_AiGenerated DEFAULT FALSE,
    CreatedByUserId    INT NOT NULL,
    CreatedAtUtc       timestamptz(0) NOT NULL CONSTRAINT DF_PromptVersions_Created DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT UQ_PromptVersions_PromptNumber UNIQUE (PromptLibraryId, VersionNumber),
    CONSTRAINT CK_PromptVersions_VersionNumber CHECK (VersionNumber >= 1)
);
