-- Tables owned by the notify schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE notify.NotificationTypes
(
    NotificationTypeId    smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_NotificationTypes PRIMARY KEY,
    TypeCode              VARCHAR(50) NOT NULL CONSTRAINT UQ_NotificationTypes_Code UNIQUE,
    CategoryCode          VARCHAR(30) NOT NULL,
    DefaultPriority       VARCHAR(10) NOT NULL,
    IsMandatory           boolean NOT NULL CONSTRAINT DF_NotificationTypes_Mandatory DEFAULT FALSE,
    DefaultEnabled        boolean NOT NULL CONSTRAINT DF_NotificationTypes_Enabled DEFAULT TRUE,
    CONSTRAINT CK_NotificationTypes_Priority CHECK (DefaultPriority IN ('Low','Normal','High','Critical'))
);

CREATE TABLE notify.UserNotificationPreferences
(
    UserId                INT NOT NULL,
    NotificationTypeId    SMALLINT NOT NULL,
    InAppEnabled          boolean NOT NULL CONSTRAINT DF_NotificationPreferences_InApp DEFAULT TRUE,
    EmailEnabled          boolean NOT NULL CONSTRAINT DF_NotificationPreferences_Email DEFAULT FALSE,
    ReminderLeadMinutes   INT NULL,
    CONSTRAINT PK_UserNotificationPreferences PRIMARY KEY (UserId, NotificationTypeId),
    CONSTRAINT CK_NotificationPreferences_Lead CHECK (ReminderLeadMinutes IS NULL OR ReminderLeadMinutes >= 0)
);

CREATE TABLE notify.Notifications
(
    NotificationId        bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Notifications PRIMARY KEY,
    NotificationTypeId    SMALLINT NOT NULL,
    ActorUserId           INT NULL,
    ProjectId             INT NULL,
    TaskId                BIGINT NULL,
    ChangeRequestId       BIGINT NULL,
    AttendanceCorrectionId BIGINT NULL,
    LeaveRequestId        BIGINT NULL,
    Title                 varchar(200) NOT NULL,
    SafePreviewText       varchar(500) NULL,
    PriorityCode          VARCHAR(10) NOT NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_Notifications_Created DEFAULT (CURRENT_TIMESTAMP),
    ExpiresAtUtc          timestamptz(0) NULL,
    CONSTRAINT CK_Notifications_Title CHECK (char_length(btrim(Title)) > 0),
    CONSTRAINT CK_Notifications_Priority CHECK (PriorityCode IN ('Low','Normal','High','Critical')),
    CONSTRAINT CK_Notifications_Expiry CHECK (ExpiresAtUtc IS NULL OR ExpiresAtUtc > CreatedAtUtc)
);

CREATE TABLE notify.UserNotifications
(
    NotificationId        BIGINT NOT NULL,
    RecipientUserId       INT NOT NULL,
    DeliveryStatus        VARCHAR(20) NOT NULL CONSTRAINT DF_UserNotifications_Delivery DEFAULT ('Pending'),
    DeliveredAtUtc        timestamptz(0) NULL,
    ReadAtUtc             timestamptz(0) NULL,
    OpenedAtUtc           timestamptz(0) NULL,
    ClearedAtUtc          timestamptz(0) NULL,
    CONSTRAINT PK_UserNotifications PRIMARY KEY (NotificationId, RecipientUserId),
    CONSTRAINT CK_UserNotifications_Delivery CHECK (DeliveryStatus IN ('Pending','Delivered','Failed','Suppressed'))
);
