-- Tables owned by the config schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE config.SettingDefinitions
(
    SettingDefinitionId   smallint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_SettingDefinitions PRIMARY KEY,
    SettingKey            VARCHAR(100) NOT NULL CONSTRAINT UQ_SettingDefinitions_Key UNIQUE,
    CategoryCode          VARCHAR(40) NOT NULL,
    DataTypeCode          VARCHAR(20) NOT NULL,
    DefaultValue          text NULL,
    IsSecret              boolean NOT NULL CONSTRAINT DF_SettingDefinitions_Secret DEFAULT FALSE,
    IsUserConfigurable    boolean NOT NULL CONSTRAINT DF_SettingDefinitions_User DEFAULT FALSE,
    Description           varchar(500) NULL,
    CONSTRAINT CK_SettingDefinitions_Type CHECK (DataTypeCode IN ('String','Integer','numeric','Boolean','Json','Encrypted'))
);

CREATE TABLE config.OrganizationSettingValues
(
    OrganizationId        INT NOT NULL,
    SettingDefinitionId   SMALLINT NOT NULL,
    SettingValue          text NOT NULL,
    UpdatedByUserId       INT NOT NULL,
    UpdatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_OrganizationSettings_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion            bigint NOT NULL DEFAULT 1,
    CONSTRAINT PK_OrganizationSettingValues PRIMARY KEY (OrganizationId, SettingDefinitionId)
);

CREATE TABLE config.UserSettingValues
(
    UserId                INT NOT NULL,
    SettingDefinitionId   SMALLINT NOT NULL,
    SettingValue          text NOT NULL,
    UpdatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_UserSettings_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion            bigint NOT NULL DEFAULT 1,
    CONSTRAINT PK_UserSettingValues PRIMARY KEY (UserId, SettingDefinitionId)
);
