-- Tables owned by the audit schema.
-- Foreign keys are added after all 70 tables exist.

CREATE TABLE audit.AuditEvents
(
    AuditEventId          bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_AuditEvents PRIMARY KEY,
    OrganizationId        INT NOT NULL,
    ActorUserId           INT NULL,
    ImpersonatedByUserId  INT NULL,
    ActionCode            VARCHAR(60) NOT NULL,
    EntityTypeCode        VARCHAR(40) NOT NULL,
    EntityIdText          varchar(100) NOT NULL,
    ProjectId             INT NULL,
    TaskId                BIGINT NULL,
    AttendanceRecordId    BIGINT NULL,
    UserRoleId            BIGINT NULL,
    Reason                varchar(1000) NULL,
    PermissionSnapshot    varchar(200) NULL,
    CorrelationId         uuid NOT NULL CONSTRAINT DF_AuditEvents_Correlation DEFAULT (gen_random_uuid()),
    IpAddress             VARCHAR(45) NULL,
    OccurredAtUtc         timestamptz(0) NOT NULL CONSTRAINT DF_AuditEvents_Occurred DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT CK_AuditEvents_Action CHECK (char_length(btrim(ActionCode)) > 0),
    CONSTRAINT CK_AuditEvents_Entity CHECK (char_length(btrim(EntityTypeCode)) > 0 AND char_length(btrim(EntityIdText)) > 0)
);

CREATE TABLE audit.AuditEventChanges
(
    AuditEventChangeId    bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_AuditEventChanges PRIMARY KEY,
    AuditEventId          BIGINT NOT NULL,
    FieldName             varchar(128) NOT NULL,
    OldValue              text NULL,
    NewValue              text NULL,
    IsSensitive           boolean NOT NULL CONSTRAINT DF_AuditEventChanges_Sensitive DEFAULT FALSE,
    CONSTRAINT UQ_AuditEventChanges_Field UNIQUE (AuditEventId, FieldName),
    CONSTRAINT CK_AuditEventChanges_Field CHECK (char_length(btrim(FieldName)) > 0)
);
