-- Project Management Approval Workflow: Team Lead requests -> Admin approves/rejects -> the
-- original project action (edit/archive/delete/restore/permanent-delete) executes. Modeled after
-- public.worksync_hr_requests' shape (backend/src/routes/hrRequestRoutes.ts) -- flat table, a
-- RequestType discriminator, JSON payload for arbitrary "requested changes", single
-- Pending/Approved/Rejected status -- but implemented as a real versioned table (like
-- work.TaskChangeRequests) since Projects already live in real tables, unlike HR requests'
-- historical hand-created-table shortcut.
--
-- FK_ProjectApprovalRequests_Project cascades on delete: once a project is permanently deleted,
-- its historical approval-request rows no longer have independent meaning (the durable audit
-- trail for "who approved what" already lives in audit.AuditEvents via recordActivitySafe, which
-- remains immutable and untouched by this table or this feature).
CREATE TABLE work.ProjectApprovalRequests
(
    ApprovalRequestId    bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ProjectApprovalRequests PRIMARY KEY,
    ProjectId             INT NOT NULL,
    RequestType           VARCHAR(30) NOT NULL,
    RequestedByUserId     INT NOT NULL,
    RequestedChangesJson  text NULL,
    Reason                varchar(1000) NOT NULL,
    RequestStatus         VARCHAR(20) NOT NULL CONSTRAINT DF_ProjectApprovalRequests_Status DEFAULT ('Pending'),
    ReviewedByUserId      INT NULL,
    DecisionReason        varchar(1000) NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_ProjectApprovalRequests_Created DEFAULT (CURRENT_TIMESTAMP),
    DecidedAtUtc          timestamptz(0) NULL,
    CONSTRAINT CK_ProjectApprovalRequests_Type CHECK
            (RequestType IN ('PROJECT_CREATE','PROJECT_EDIT','PROJECT_ARCHIVE','PROJECT_RESTORE','PROJECT_DELETE','PROJECT_PERMANENT_DELETE')),
    CONSTRAINT CK_ProjectApprovalRequests_Status CHECK
            (RequestStatus IN ('Pending','Approved','Rejected')),
    CONSTRAINT CK_ProjectApprovalRequests_Reason CHECK (char_length(btrim(Reason)) > 0),
    CONSTRAINT CK_ProjectApprovalRequests_ChangesJson CHECK
            (RequestedChangesJson IS NULL OR config.is_valid_json(RequestedChangesJson)),
    -- A request is either untouched-Pending, or fully decided (reviewer + decision time both
    -- set) -- never a half-decided row.
    CONSTRAINT CK_ProjectApprovalRequests_Decision CHECK
            ((RequestStatus = 'Pending' AND ReviewedByUserId IS NULL AND DecidedAtUtc IS NULL) OR
             (RequestStatus <> 'Pending' AND ReviewedByUserId IS NOT NULL AND DecidedAtUtc IS NOT NULL))
);

ALTER TABLE work.ProjectApprovalRequests
    ADD CONSTRAINT FK_ProjectApprovalRequests_Project FOREIGN KEY (ProjectId)
        REFERENCES work.Projects(ProjectId) ON DELETE CASCADE;

ALTER TABLE work.ProjectApprovalRequests
    ADD CONSTRAINT FK_ProjectApprovalRequests_RequestedBy FOREIGN KEY (RequestedByUserId) REFERENCES iam.Users(UserId);

ALTER TABLE work.ProjectApprovalRequests
    ADD CONSTRAINT FK_ProjectApprovalRequests_ReviewedBy FOREIGN KEY (ReviewedByUserId) REFERENCES iam.Users(UserId);

CREATE INDEX IX_ProjectApprovalRequests_Pending ON work.ProjectApprovalRequests(RequestStatus, CreatedAtUtc);
CREATE INDEX IX_ProjectApprovalRequests_Project ON work.ProjectApprovalRequests(ProjectId);
CREATE INDEX IX_ProjectApprovalRequests_Requester ON work.ProjectApprovalRequests(RequestedByUserId);
