-- Persist the Project Management Approval Workflow in existing WorkSync databases.
--
-- database/25_project_approvals.sql already installs this table for databases created from the
-- current one-time baseline. Existing Supabase environments must apply this versioned migration.
-- All identifiers intentionally remain unquoted, matching the rest of the WorkSync schema and
-- PostgreSQL's lowercase identifier folding used by projectApproval.repository.ts.

BEGIN;

-- Avoid creating a duplicate if an early manual deployment used a quoted mixed-case table name.
DO $$
BEGIN
    IF to_regclass('work.projectapprovalrequests') IS NULL
       AND to_regclass('"work"."ProjectApprovalRequests"') IS NOT NULL THEN
        EXECUTE 'ALTER TABLE "work"."ProjectApprovalRequests" RENAME TO projectapprovalrequests';
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS work.ProjectApprovalRequests
(
    ApprovalRequestId    bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ProjectApprovalRequests PRIMARY KEY,
    ProjectId             INT NOT NULL,
    RequestType           VARCHAR(30) NOT NULL,
    RequestedByUserId     INT NOT NULL,
    RequestedChangesJson  text NULL,
    Reason                varchar(1000) NOT NULL,
    RequestStatus         VARCHAR(20) NOT NULL CONSTRAINT DF_ProjectApprovalRequests_Status DEFAULT ('Pending'),
    ReviewedByUserId      INT NULL,
    DecisionReason        varchar(1000) NULL,
    CreatedAtUtc          timestamptz(0) NOT NULL CONSTRAINT DF_ProjectApprovalRequests_Created DEFAULT (CURRENT_TIMESTAMP),
    DecidedAtUtc          timestamptz(0) NULL,
    CONSTRAINT CK_ProjectApprovalRequests_Type CHECK
            (RequestType IN ('PROJECT_EDIT','PROJECT_ARCHIVE','PROJECT_DELETE','PROJECT_RESTORE','PROJECT_PERMANENT_DELETE')),
    CONSTRAINT CK_ProjectApprovalRequests_Status CHECK
            (RequestStatus IN ('Pending','Approved','Rejected')),
    CONSTRAINT CK_ProjectApprovalRequests_Reason CHECK (char_length(btrim(Reason)) > 0),
    CONSTRAINT CK_ProjectApprovalRequests_ChangesJson CHECK
            (RequestedChangesJson IS NULL OR config.is_valid_json(RequestedChangesJson)),
    CONSTRAINT CK_ProjectApprovalRequests_Decision CHECK
            ((RequestStatus = 'Pending' AND ReviewedByUserId IS NULL AND DecidedAtUtc IS NULL) OR
             (RequestStatus <> 'Pending' AND ReviewedByUserId IS NOT NULL AND DecidedAtUtc IS NOT NULL))
);

-- Widen the RequestType check for databases where this table was created before 'PROJECT_EDIT'
-- was added to the workflow -- CREATE TABLE IF NOT EXISTS above is a no-op on an already-existing
-- table, so it never retroactively fixes a stale constraint on its own. Drop-and-recreate
-- (idempotent, matching this file's own FK-patching pattern below) keeps this migration safe to
-- rerun against any existing WorkSync database, regardless of when its approval-requests table
-- was first created.
ALTER TABLE work.ProjectApprovalRequests
    DROP CONSTRAINT IF EXISTS CK_ProjectApprovalRequests_Type;
ALTER TABLE work.ProjectApprovalRequests
    ADD CONSTRAINT CK_ProjectApprovalRequests_Type CHECK
        (RequestType IN ('PROJECT_EDIT','PROJECT_ARCHIVE','PROJECT_DELETE','PROJECT_RESTORE','PROJECT_PERMANENT_DELETE'));

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_projectapprovalrequests_project'
          AND conrelid = 'work.projectapprovalrequests'::regclass
    ) THEN
        ALTER TABLE work.ProjectApprovalRequests
            ADD CONSTRAINT FK_ProjectApprovalRequests_Project FOREIGN KEY (ProjectId)
                REFERENCES work.Projects(ProjectId) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_projectapprovalrequests_requestedby'
          AND conrelid = 'work.projectapprovalrequests'::regclass
    ) THEN
        ALTER TABLE work.ProjectApprovalRequests
            ADD CONSTRAINT FK_ProjectApprovalRequests_RequestedBy FOREIGN KEY (RequestedByUserId)
                REFERENCES iam.Users(UserId);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_projectapprovalrequests_reviewedby'
          AND conrelid = 'work.projectapprovalrequests'::regclass
    ) THEN
        ALTER TABLE work.ProjectApprovalRequests
            ADD CONSTRAINT FK_ProjectApprovalRequests_ReviewedBy FOREIGN KEY (ReviewedByUserId)
                REFERENCES iam.Users(UserId);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS IX_ProjectApprovalRequests_Pending
    ON work.ProjectApprovalRequests(RequestStatus, CreatedAtUtc);
CREATE INDEX IF NOT EXISTS IX_ProjectApprovalRequests_Project
    ON work.ProjectApprovalRequests(ProjectId);
CREATE INDEX IF NOT EXISTS IX_ProjectApprovalRequests_Requester
    ON work.ProjectApprovalRequests(RequestedByUserId);

COMMIT;
