-- Multi-Team Project Architecture: introduces a Team layer between a Project and its members.
--
-- A Project now owns one or more work.ProjectTeams. Each team has exactly one Team Lead and at
-- least one additional member (enforced by the application layer; the schema here guarantees the
-- "one person, one team per project" invariant). Tasks carry an optional TeamId so a task belongs
-- to the team whose lead created/owns it, and an Admin-created task targets a Team rather than an
-- individual (the team's lead then assigns it within their team).
--
-- Additive and safe to run more than once. Existing projects simply have no team rows, and their
-- tasks have a NULL TeamId -- the application falls back to the existing project-lead model for
-- those, so nothing already working is disturbed.

-- A team within a project. TeamName is unique per project; Description explains the team's
-- responsibility (required, mirroring how work.Projects requires a non-empty Description).
CREATE TABLE IF NOT EXISTS work.ProjectTeams
(
    TeamId            bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_ProjectTeams PRIMARY KEY,
    ProjectId         INT NOT NULL,
    TeamName          varchar(150) NOT NULL,
    Description       varchar(2000) NOT NULL,
    CreatedByUserId   INT NOT NULL,
    CreatedAtUtc      timestamptz(0) NOT NULL CONSTRAINT DF_ProjectTeams_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc      timestamptz(0) NOT NULL CONSTRAINT DF_ProjectTeams_Updated DEFAULT (CURRENT_TIMESTAMP),
    RowVersion        bigint NOT NULL DEFAULT 1,
    CONSTRAINT UQ_ProjectTeams_Project_Name UNIQUE (ProjectId, TeamName),
    CONSTRAINT CK_ProjectTeams_Name CHECK (char_length(btrim(TeamName)) > 0),
    CONSTRAINT CK_ProjectTeams_Description CHECK (char_length(btrim(Description)) > 0)
);

-- A person's membership in a specific team of a project. ProjectId is denormalized onto this
-- table so the "one person, one team per project" invariant can be enforced by a plain UNIQUE
-- constraint (a cross-table unique index would require a trigger). IsLead marks exactly one
-- member per team as its Team Lead; the application enforces "exactly one lead and >= 1 other
-- member" on top of this, and a partial unique index below guarantees at most one lead per team.
CREATE TABLE IF NOT EXISTS work.TeamMembers
(
    TeamMemberId      bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_TeamMembers PRIMARY KEY,
    TeamId            bigint NOT NULL,
    ProjectId         INT NOT NULL,
    UserId            INT NOT NULL,
    IsLead            boolean NOT NULL CONSTRAINT DF_TeamMembers_IsLead DEFAULT FALSE,
    AddedByUserId     INT NOT NULL,
    JoinedAtUtc       timestamptz(0) NOT NULL CONSTRAINT DF_TeamMembers_Joined DEFAULT (CURRENT_TIMESTAMP),
    LeftAtUtc         timestamptz(0) NULL,
    RemovedByUserId   INT NULL,
    CONSTRAINT UQ_TeamMembers_Project_User UNIQUE (ProjectId, UserId),
    CONSTRAINT UQ_TeamMembers_Team_User UNIQUE (TeamId, UserId),
    CONSTRAINT CK_TeamMembers_Left CHECK
            ((LeftAtUtc IS NULL AND RemovedByUserId IS NULL) OR
             (LeftAtUtc IS NOT NULL AND RemovedByUserId IS NOT NULL AND LeftAtUtc >= JoinedAtUtc))
);

-- At most one lead per team (the application additionally requires exactly one).
CREATE UNIQUE INDEX IF NOT EXISTS UQ_TeamMembers_OneLead
    ON work.TeamMembers (TeamId)
    WHERE IsLead IS TRUE AND LeftAtUtc IS NULL;

-- A task belongs to the team whose lead created it (Team Lead-created tasks), or the team an
-- Admin targeted it at (Admin-created team tasks awaiting the team lead's assignment).
-- AssignmentStatus distinguishes "created, awaiting the team lead to assign it to a member"
-- ('NeedsTeamAssignment', the Admin->Team handoff) from 'Assigned' (a concrete member owns it).
ALTER TABLE work.Tasks ADD COLUMN IF NOT EXISTS TeamId bigint NULL;
ALTER TABLE work.Tasks ADD COLUMN IF NOT EXISTS AssignmentStatus VARCHAR(30) NULL
    CONSTRAINT CK_Tasks_AssignmentStatus CHECK
        (AssignmentStatus IS NULL OR AssignmentStatus IN ('NeedsTeamAssignment','Assigned'));

CREATE INDEX IF NOT EXISTS IX_Tasks_Team ON work.Tasks(TeamId);

-- Cross-team subtask transfer: a Team Lead hands one of their team's subtasks to another team.
-- The subtask keeps its row/assignees; Admin approval flips its TeamId to the target team, so the
-- receiving team's lead gains ownership. Mirrors the ProjectApprovalRequests review model but is
-- task-scoped (and lives here because it only exists for team-enabled projects).
CREATE TABLE IF NOT EXISTS work.SubtaskTransferRequests
(
    RequestId        bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_SubtaskTransferRequests PRIMARY KEY,
    SubtaskId        bigint NOT NULL,
    ProjectId        INT NOT NULL,
    FromTeamId       bigint NULL,
    ToTeamId         bigint NOT NULL,
    RequestedByUserId INT NOT NULL,
    RequestReason    varchar(500) NULL,
    RequestStatus    varchar(20) NOT NULL CONSTRAINT DF_SubtaskTransferRequests_Status DEFAULT 'Pending',
    RequestedAtUtc   timestamptz(0) NOT NULL CONSTRAINT DF_SubtaskTransferRequests_Requested DEFAULT (CURRENT_TIMESTAMP),
    DecidedAtUtc     timestamptz(0) NULL,
    DecidedByUserId  INT NULL,
    DecisionReason   varchar(500) NULL,
    CONSTRAINT CK_SubtaskTransferRequests_Status CHECK
        (RequestStatus IN ('Pending','Approved','Rejected')),
    CONSTRAINT CK_SubtaskTransferRequests_Decided CHECK
        ((RequestStatus = 'Pending' AND DecidedAtUtc IS NULL AND DecidedByUserId IS NULL) OR
         (RequestStatus <> 'Pending' AND DecidedAtUtc IS NOT NULL AND DecidedByUserId IS NOT NULL))
);

-- Foreign keys (mirrors database/13_foreign_keys.sql's one-ALTER-per-relationship style).
ALTER TABLE work.ProjectTeams
    ADD CONSTRAINT FK_ProjectTeams_Project FOREIGN KEY (ProjectId)
        REFERENCES work.Projects(ProjectId) ON DELETE CASCADE;

ALTER TABLE work.ProjectTeams
    ADD CONSTRAINT FK_ProjectTeams_CreatedBy FOREIGN KEY (CreatedByUserId)
        REFERENCES iam.Users(UserId);

ALTER TABLE work.TeamMembers
    ADD CONSTRAINT FK_TeamMembers_Team FOREIGN KEY (TeamId)
        REFERENCES work.ProjectTeams(TeamId) ON DELETE CASCADE;

ALTER TABLE work.TeamMembers
    ADD CONSTRAINT FK_TeamMembers_Project FOREIGN KEY (ProjectId)
        REFERENCES work.Projects(ProjectId) ON DELETE CASCADE;

ALTER TABLE work.TeamMembers
    ADD CONSTRAINT FK_TeamMembers_User FOREIGN KEY (UserId)
        REFERENCES iam.Users(UserId);

ALTER TABLE work.Tasks
    ADD CONSTRAINT FK_Tasks_Team FOREIGN KEY (TeamId)
        REFERENCES work.ProjectTeams(TeamId) ON DELETE SET NULL;

ALTER TABLE work.SubtaskTransferRequests
    ADD CONSTRAINT FK_SubtaskTransferRequests_Subtask FOREIGN KEY (SubtaskId)
        REFERENCES work.Tasks(TaskId) ON DELETE CASCADE;

ALTER TABLE work.SubtaskTransferRequests
    ADD CONSTRAINT FK_SubtaskTransferRequests_Project FOREIGN KEY (ProjectId)
        REFERENCES work.Projects(ProjectId) ON DELETE CASCADE;

ALTER TABLE work.SubtaskTransferRequests
    ADD CONSTRAINT FK_SubtaskTransferRequests_FromTeam FOREIGN KEY (FromTeamId)
        REFERENCES work.ProjectTeams(TeamId) ON DELETE SET NULL;

ALTER TABLE work.SubtaskTransferRequests
    ADD CONSTRAINT FK_SubtaskTransferRequests_ToTeam FOREIGN KEY (ToTeamId)
        REFERENCES work.ProjectTeams(TeamId);

ALTER TABLE work.SubtaskTransferRequests
    ADD CONSTRAINT FK_SubtaskTransferRequests_RequestedBy FOREIGN KEY (RequestedByUserId)
        REFERENCES iam.Users(UserId);

-- Notification types for the new team workflows (idempotent; see database/18_notify_seed.sql and
-- backend/src/db/pool.ts's bootstrap for the same TypeCode/CategoryCode/DefaultPriority rows).
INSERT INTO notify.NotificationTypes (TypeCode, CategoryCode, DefaultPriority, IsMandatory, DefaultEnabled)
VALUES
    ('team_member_removed_needs_reassignment', 'Project', 'High', FALSE, TRUE),
    ('team_member_moved',                       'Project', 'High', FALSE, TRUE),
    ('admin_task_needs_team_assignment',        'Task',    'High', FALSE, TRUE),
    ('subtask_transfer_requested',              'Task',    'High', FALSE, TRUE),
    ('subtask_transfer_approved',               'Task',    'High', FALSE, TRUE),
    ('subtask_transfer_rejected',               'Task',    'Normal', FALSE, TRUE),
    ('team_lead_changed',                       'Project', 'High', FALSE, TRUE)
ON CONFLICT (TypeCode) DO NOTHING;
