-- Installs the AI Assistant prompt library (saved prompts + their version history) in existing
-- WorkSync databases. database/09_ai_tables.sql already installs these tables for databases
-- created from the current one-time baseline. Previously saved prompts lived only in the
-- backend's in-memory PromptStore and were silently lost whenever the backend restarted (or, on
-- Vercel, whenever a serverless instance was recycled) -- this migration gives them durable
-- storage. Idempotent: safe to run more than once.

BEGIN;

CREATE TABLE IF NOT EXISTS ai.PromptLibraries
(
    PromptLibraryId        bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_PromptLibraries PRIMARY KEY,
    UserId                 INT NOT NULL,
    ProjectId              INT NULL,
    TaskId                 BIGINT NULL,
    CategoryCode           VARCHAR(40) NOT NULL,
    Title                  VARCHAR(200) NOT NULL,
    StyleCode              VARCHAR(30) NOT NULL CONSTRAINT DF_PromptLibraries_Style DEFAULT ('Default'),
    AdditionalInstructions TEXT NULL,
    IsArchived             boolean NOT NULL CONSTRAINT DF_PromptLibraries_Archived DEFAULT FALSE,
    CreatedAtUtc           timestamptz(0) NOT NULL CONSTRAINT DF_PromptLibraries_Created DEFAULT (CURRENT_TIMESTAMP),
    UpdatedAtUtc           timestamptz(0) NOT NULL CONSTRAINT DF_PromptLibraries_Updated DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS ai.PromptVersions
(
    PromptVersionId    bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_PromptVersions PRIMARY KEY,
    PromptLibraryId    bigint NOT NULL,
    VersionNumber      INT NOT NULL,
    Content            TEXT NOT NULL,
    IsAiGenerated      boolean NOT NULL CONSTRAINT DF_PromptVersions_AiGenerated DEFAULT FALSE,
    CreatedByUserId    INT NOT NULL,
    CreatedAtUtc       timestamptz(0) NOT NULL CONSTRAINT DF_PromptVersions_Created DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT UQ_PromptVersions_PromptNumber UNIQUE (PromptLibraryId, VersionNumber),
    CONSTRAINT CK_PromptVersions_VersionNumber CHECK (VersionNumber >= 1)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_promptlibraries_user'
          AND conrelid = 'ai.promptlibraries'::regclass
    ) THEN
        ALTER TABLE ai.PromptLibraries
            ADD CONSTRAINT FK_PromptLibraries_User FOREIGN KEY (UserId) REFERENCES iam.Users(UserId);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_promptlibraries_project'
          AND conrelid = 'ai.promptlibraries'::regclass
    ) THEN
        ALTER TABLE ai.PromptLibraries
            ADD CONSTRAINT FK_PromptLibraries_Project FOREIGN KEY (ProjectId) REFERENCES work.Projects(ProjectId);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_promptlibraries_task'
          AND conrelid = 'ai.promptlibraries'::regclass
    ) THEN
        ALTER TABLE ai.PromptLibraries
            ADD CONSTRAINT FK_PromptLibraries_Task FOREIGN KEY (TaskId) REFERENCES work.Tasks(TaskId);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_promptversions_library'
          AND conrelid = 'ai.promptversions'::regclass
    ) THEN
        ALTER TABLE ai.PromptVersions
            ADD CONSTRAINT FK_PromptVersions_Library FOREIGN KEY (PromptLibraryId)
                REFERENCES ai.PromptLibraries(PromptLibraryId) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_promptversions_createdby'
          AND conrelid = 'ai.promptversions'::regclass
    ) THEN
        ALTER TABLE ai.PromptVersions
            ADD CONSTRAINT FK_PromptVersions_CreatedBy FOREIGN KEY (CreatedByUserId) REFERENCES iam.Users(UserId);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS IX_PromptLibraries_UserArchived ON ai.PromptLibraries(UserId, IsArchived, UpdatedAtUtc DESC);
CREATE INDEX IF NOT EXISTS IX_PromptVersions_LibraryNumber ON ai.PromptVersions(PromptLibraryId, VersionNumber);

COMMIT;
