import assert from 'node:assert/strict';
import test from 'node:test';
import { newDb } from 'pg-mem';

test('PostgreSQL indexes reject email and username duplicates case-insensitively', () => {
  const db = newDb();
  db.public.none(`
    CREATE SCHEMA iam;
    CREATE TABLE iam.users (
      userid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organizationid int NOT NULL,
      email varchar(254) NOT NULL,
      username varchar(80) NOT NULL
    );
    CREATE UNIQUE INDEX ux_users_organization_email_ci
      ON iam.users (organizationid, lower(email));
    CREATE UNIQUE INDEX ux_users_organization_username_ci
      ON iam.users (organizationid, lower(username));
    INSERT INTO iam.users (organizationid, email, username)
      VALUES (1, 'person@example.com', 'person.one');
  `);
  assert.throws(
    () => db.public.none("INSERT INTO iam.users (organizationid, email, username) VALUES (1, 'PERSON@example.com', 'another')"),
    /unique/i
  );
  assert.throws(
    () => db.public.none("INSERT INTO iam.users (organizationid, email, username) VALUES (1, 'other@example.com', 'PERSON.ONE')"),
    /unique/i
  );
});
